// --- DATA DICTIONARIES ---
        const i18n = {
            ku: {
                title: "Pratîka Îbranî",
                subtitle: "Li ser bingeha Îbranî ji bo Axêverên Kurmancî (Ji hêla Brett Goldberg û Reuven Koret ve)",
                toc_title: "Naverok",
                toc_alpha_title: "Elîfbê",
                toc_alpha_desc: "Tîp, Nikud, Flashcards û Lîstik",
                toc_ch1_title: "Beş 1",
                toc_ch1_desc: "Bêjeyên destpêkê û rêziman",
                toc_ch2_title: "Beş 2",
                toc_ch2_desc: "Silav, nasîn û rêziman",
                toc_b1_title: "Beş 1: Elîfbêya Îbranî",
                toc_b1_p1: "Elîfbê",
                toc_b1_p2: "Beş 1: Bêje û Rêziman",
                toc_b1_p3: "Lîstikên Bêjeyan",
                toc_b2_title: "Beş 2: Silav û Nasîn",
                toc_b2_desc: "Xwendina Diyalog, Bêje û Rêziman",
                btn_ref: "Çavkanî",
                btn_flash: "Kartên Bîranînê",
                btn_quiz: "Pirsname",
                cat_letters: "Tîp",
                cat_nikud: "Dengdêr (Nikud)",
                col_heb: "Îbranî",
                col_name: "Nav",
                col_sound: "Deng",
                col_ex: "Mînak",
                fc_instruction: "Ji bo dîtina deng û wateyê li ser kartê bitikînin.",
                fc_sound_label: "DENG",
                fc_ex_label: "MÎNAK",
                fc_flip: "Bizivire",
                fc_next: "Pêşîn",
                course_home: "Course Home",
                nav_lesson: "Lesson",
                nav_games: "Games",
                quiz_ready: "Amade ye?",
                quiz_desc: "Hûn ê ji bo her yek ji wan pirsan bistînin.",
                quiz_start: "Destpêkirina Pirsnameyê",
                quiz_q_name_letters: "Navê vê tîpê çi ye?",
                quiz_q_sound_letters: "Dengê vê tîpê çi ye?",
                quiz_q_name_nikud: "Navê vê dengdêrê çi ye?",
                quiz_q_sound_nikud: "Dengê vê dengdêrê çi ye?",
                quiz_progress: "Pirs {current}/{total}",
                quiz_score: "Puan: {score}",
                quiz_next: "Pirsa Pêşîn",
                quiz_done: "Pirsname Qediya!",
                quiz_score_msg: "Te <span class='font-bold text-blue-600 dark:text-blue-400 text-2xl sm:text-3xl'>{score}</span> ji <span class='font-bold text-slate-800 dark:text-slate-100 text-2xl sm:text-3xl'>{total}</span> girt.",
                quiz_play_again: "Dîsa Bileyze",
                alpha_games_title: "Lîstikên Elîfbêyê",
                alpha_tab_letters: "Hevcotkirina Tîpan",
                alpha_tab_nikud: "Hevcotkirina Nikudan",
                alpha_inst_letters: "Her tîpek Îbranî bi dengê wê re hevcot bike.",
                alpha_inst_nikud: "Her nikudê bi dengê nivîskî yê wê re hevcot bike.",

                // Chapter 1 texts
                alpha_title: "Elîfbêya Îbranî",
                ch1_title: "Beş 1: Bêje û Rêziman",
                b1_title: "Beş 1: Elîfbêya Îbranî",
                b1_intro: "Di vê beşê de em ê elîfbêya Îbranî (Alef-Bet) fêr bibin. 22 tîpên wê hene û ji rastê ber bi çepê tê xwendin — mîna nivîsara Kurdî ya bi alfabeya Erebî. Elîfbê 22 tîp hene. Hemû konsonant in — dengdêr bi nîşanên piçûk (nikud / ניקוד) tên nîşankirin. Di nivîsarên mezinên rojane de nikud pir caran nayên bikaranîn.",
                b1_13_title: "Beşa 1.3 — Bêjeyên Destpêkê",
                b1_14_title: "Beşa 1.4 — Rêzimana Beşê 1: Alîyê Nivîsandinê",
                b1_14_p1: "Îbranî ji rastê ber bi çepê tê nivîsandin (mîna Erebî). Gava ku du zimanên cuda di hevokekê de werin bikaranîn — mîna Kurmancî û Îbranî — aliyê nivîsandinê diguhere. Ev jê re 'bidireksiyon' (du alî) dibêjin.",
                b1_14_p2: "Di dema xwendina Îbranî de gava tîpek nasnakirî be, ji navê wê dest pê bike. Mînak: ב = 'Bet' — deng 'b' e.",
                hw_title: "Spartek / שיעורי בית",
                hw_instr: "Rêwerzên wergêranê: Van pirsên jêrîn bersiv bidin.",

                // Game texts
                tab_wb: "Peyv Çêkirin",
                tab_cp: "Hevcotkirin",
                tab_sb: "Hevok Çêkirin",
                tab_cg: "Lêkera bûn",
                inst_wb: "Tîpan bitikînin da ku peyva rast çêbikin.",
                b2_im_a: "Ez",
                gender_man: "Mêr",
                gender_woman: "Jin",
                inst_cp: "Peyvên li milê çepê bi wergera wan a Îbranî ya li milê rastê ve girêbidin.",
                inst_sb: "Bêjeyan bitikînin da ku hevoka rast çêbikin.",
                inst_cg: "Pêşî stûna Îbraniyê, paşê stûna şiyandinê ji jor heta jêr tije bike.",
                cg_col_translation: "Cînavk",
                cg_col_hebrew: "Îbranî",
                cg_col_to_be: "Bûn",
                cg_phase_forms: "Naha şiyandin e.",
                cg_done: "Te tablo qedand.",
                btn_check: "Kontrol bike",
                btn_try_again: "Dîsa Biceribîne",
                btn_next: "Pêşîn",
                btn_next_round: "Gera Pêşîn",
                msg_correct: "Rast e!",
                msg_wrong: "Çewt e.",
                msg_correct_answer: "Bersiva rast",
                msg_win: "Te hemû qedandin!",
                msg_round_win: "Gera {round} qediya! Dom bike.",
                pronunciation: "Dengxwandin",
                
                // Chapter 2 texts
                b2_title: "Beş 2: Silav û Nasîn / ברכות והיכרות",
                dialog_title: "Diyalog / דיאלוג",
                vocab_title: "Bêjeyên Nû / אוצר מילים",
                b2_gram_title: "Rêzimana Beşê 1: Lêkera «bûn» û Cînavkên Kesî",
                b2_gram_p1: "Di Kurmancî de lêkera «bûn» di dema niha de bi vî awayî tê bikaranîn: ez im, tu yî, ew e, em in, hûn in, ew in. Mînak: «Ez baş im» û «Tu li ku yî?».",
                b2_gram_p2: "Cînavkên kesî yên Kurmancî ev in: ez (min), tu (te), ew (wî/wê), em (me), hûn (we), ew (wan). Forma yekem ji bo mijarê tê bikaranîn; forma duyem ji bo tişta lêkerên gerguhêz tê bikaranîn.",
                b2_gram_p3: "Pirsa «çawa?» ji bo pirskirina halê kesekî tê bikaranîn. Bersiva asayî: «Ez baş im, spas» an «Ne xirab e».",
                b2_gram_p4: "Ji bo xatirxwestinê: «Xwedahafiz» wekî «Xudê te bibe nîgehdar» tê bikaranîn. Di Îbranî de hevwateya wê «לְהִתְרָאוֹת» (lehitraot) e.",
                b2_gram_table_title: "Lêkera «bûn» — Dema Niha  [Dema Niha]  |  Kurmancî: bûn  |  עברית: לִהְיוֹת",
                hw_instr_trans: "Rêwerzên wergêranê: Van hevokên Kurmancî bo Îbranî wergerînin.",

                // Table Headers
                th_kurmanci: "Kurmancî",
                th_ibrani: "Îbranî",
                th_dengderi: "Dengxwandin",
                th_cinavk: "Cînavk",
                th_shiyandin: "Şiyandin / הַטָּיָה"
            },
            en: {
                title: "Hebrew Practice",
                subtitle: "Based on Hebrew for Kurmanji Speakers (by Brett Goldberg and Reuven Koret)",
                toc_title: "Table of Contents",
                toc_alpha_title: "Alphabet",
                toc_alpha_desc: "Letters, Nikud, Flashcards & Games",
                toc_ch1_title: "Chapter 1",
                toc_ch1_desc: "First words and grammar",
                toc_ch2_title: "Chapter 2",
                toc_ch2_desc: "Greetings, introductions, and grammar",
                toc_b1_title: "Chapter 1: The Hebrew Alphabet",
                toc_b1_p1: "Alphabet",
                toc_b1_p2: "Chapter 1: Vocabulary & Grammar",
                toc_b1_p3: "Word Games",
                toc_b2_title: "Chapter 2: Greetings & Introductions",
                toc_b2_desc: "Read Dialogues, Vocabulary & Grammar",
                btn_ref: "Reference Table",
                btn_flash: "Flashcards",
                btn_quiz: "Quiz",
                cat_letters: "Consonants",
                cat_nikud: "Vowels (Nikud)",
                col_heb: "Hebrew",
                col_name: "Name",
                col_sound: "Sound",
                col_ex: "Example",
                fc_instruction: "Click the card to reveal its sound and meaning.",
                fc_sound_label: "SOUND",
                fc_ex_label: "EXAMPLE",
                fc_flip: "Flip",
                fc_next: "Next",
                course_home: "Course Home",
                nav_lesson: "Lesson",
                nav_games: "Games",
                quiz_ready: "Ready to test?",
                quiz_desc: "You will be tested on every item in this category.",
                quiz_start: "Start Quiz",
                quiz_q_name_letters: "What is the name of this letter?",
                quiz_q_sound_letters: "What sound does this letter make?",
                quiz_q_name_nikud: "What is the name of this vowel?",
                quiz_q_sound_nikud: "What sound does this vowel make?",
                quiz_progress: "Question {current}/{total}",
                quiz_score: "Score: {score}",
                quiz_next: "Next Question",
                quiz_done: "Quiz Complete!",
                quiz_score_msg: "You scored <span class='font-bold text-blue-600 dark:text-blue-400 text-2xl sm:text-3xl'>{score}</span> out of <span class='font-bold text-slate-800 dark:text-slate-100 text-2xl sm:text-3xl'>{total}</span>.",
                quiz_play_again: "Play Again",
                alpha_games_title: "Alphabet Games",
                alpha_tab_letters: "Letters Match",
                alpha_tab_nikud: "Nikud Match",
                alpha_inst_letters: "Match each Hebrew letter with its sound.",
                alpha_inst_nikud: "Match each nikud symbol with its written vowel sound.",

                // Chapter 1 texts
                alpha_title: "The Hebrew Alphabet",
                ch1_title: "Chapter 1: Vocabulary & Grammar",
                b1_title: "Chapter 1: The Hebrew Alphabet",
                b1_intro: "In this chapter we will learn the Hebrew alphabet (Alef-Bet). It has 22 letters and is read from right to left — like the Kurdish script using the Arabic alphabet. All 22 letters are consonants — vowels are marked with small signs (nikud). In everyday large texts, nikud are often not used.",
                b1_13_title: "Section 1.3 — First Words",
                b1_14_title: "Section 1.4 — Grammar: Writing Direction",
                b1_14_p1: "Hebrew is written from right to left (like Arabic). When two different languages are used in a sentence — like Kurmanji and Hebrew — the writing direction changes. This is called 'bidirectional'.",
                b1_14_p2: "When reading Hebrew, if a letter is unfamiliar, start from its name. Example: ב = 'Bet' — sound is 'b'.",
                hw_title: "Homework / שיעורי בית",
                hw_instr: "Translation instructions: Answer the following questions.",

                // Game texts
                tab_wb: "Word Builder",
                tab_cp: "Connect Pairs",
                tab_sb: "Sentence Builder",
                tab_cg: "Conjugation",
                inst_wb: "Click letters to build the correct word.",
                b2_im_a: "I am",
                gender_man: "Man",
                gender_woman: "Woman",
                inst_cp: "Connect the words on the left with their Hebrew translation on the right.",
                inst_sb: "Click words to build the correct sentence.",
                inst_cg: "Fill the Hebrew column first, then the conjugation column from top to bottom.",
                cg_col_translation: "Translation",
                cg_col_hebrew: "Hebrew",
                cg_col_to_be: "To Be",
                cg_phase_forms: "Conjugation time.",
                cg_done: "You completed the table.",
                btn_check: "Check",
                btn_try_again: "Try Again",
                btn_next: "Next",
                btn_next_round: "Next Round",
                msg_correct: "Correct!",
                msg_wrong: "Wrong.",
                msg_correct_answer: "Correct answer",
                msg_win: "You finished them all!",
                msg_round_win: "Round {round} complete! Keep going.",
                pronunciation: "Pronunciation",
                
                // Chapter 2 texts
                b2_title: "Chapter 2: Greetings & Introductions / ברכות והיכרות",
                dialog_title: "Dialogue / דיאלוג",
                vocab_title: "New Vocabulary / אוצר מילים",
                b2_gram_title: "Chapter 1 Grammar: The Verb \"to be\" and Personal Pronouns",
                b2_gram_p1: "In Kurmanji, the verb «bûn» (to be) is used in the present tense like this: ez im, tu yî, ew e, em in, hûn in, ew in. Examples: «Ez baş im» and «Tu li ku yî?».",
                b2_gram_p2: "The personal pronouns in Kurmanji are: ez (min), tu (te), ew (wî/wê), em (me), hûn (we), ew (wan). The first form is used for the subject; the second form is used for the object with transitive verbs.",
                b2_gram_p3: "The question «çawa?» is used to ask how someone is. A common answer is «Ez baş im, spas» or «Ne xirab e».",
                b2_gram_p4: "For farewells, «Xwedahafiz» is used in the sense of «May God protect you.» In Hebrew, its equivalent is «לְהִתְרָאוֹת» (lehitraot).",
                b2_gram_table_title: "The Verb \"to be\" — Present Tense  [Present Tense]  |  Kurmanji: bûn  |  Hebrew: לִהְיוֹת",
                hw_instr_trans: "Translation instructions: Translate these Kurmanji sentences to Hebrew.",

                // Table Headers
                th_kurmanci: "Kurmanji",
                th_ibrani: "Hebrew",
                th_dengderi: "Pronunciation",
                th_cinavk: "Pronoun",
                th_shiyandin: "Conjugation"
            }
        };

        // --- DATA OBJECTS (Bilingual) ---
        const lettersData = [
            { char: 'א', nameKu: 'Elif', nameEn: 'Alef', soundKu: 'bêdeng / a / e', soundEn: 'silent / a / e', exHe: 'אָב', transKu: 'Av (bav)', transEn: 'Av (father)' },
            { char: 'ב', nameKu: 'Bê / Vê', nameEn: 'Bet / Vet', soundKu: 'b / v', soundEn: 'b / v', exHe: 'בַּיִת', transKu: 'bayit (mal)', transEn: 'bayit (house)' },
            { char: 'ג', nameKu: 'Gîmel', nameEn: 'Gimel', soundKu: 'g', soundEn: 'g', exHe: 'גָּדוֹל', transKu: 'gadol (mezin)', transEn: 'gadol (big)' },
            { char: 'ד', nameKu: 'Dalet', nameEn: 'Dalet', soundKu: 'd', soundEn: 'd', exHe: 'דֶּלֶת', transKu: 'delet (der)', transEn: 'delet (door)' },
            { char: 'ה', nameKu: 'Hê', nameEn: 'He', soundKu: 'h / bêdeng', soundEn: 'h / silent', exHe: 'הָר', transKu: 'har (çiya)', transEn: 'har (mountain)' },
            { char: 'ו', nameKu: 'Vav', nameEn: 'Vav', soundKu: 'v / û / o', soundEn: 'v / u / o', exHe: 'וָרֶד', transKu: 'vared (gul)', transEn: 'vared (rose)' },
            { char: 'ז', nameKu: 'Zeyn', nameEn: 'Zayin', soundKu: 'z', soundEn: 'z', exHe: 'זָהָב', transKu: 'zahav (zêr)', transEn: 'zahav (gold)' },
            { char: 'ח', nameKu: 'Xet', nameEn: 'Chet', soundKu: 'x (xurt)', soundEn: 'x (strong) / ch', exHe: 'חַיִּים', transKu: 'xayim (jiyan)', transEn: 'xayim (life)' },
            { char: 'ט', nameKu: 'Têt', nameEn: 'Tet', soundKu: 't', soundEn: 't', exHe: 'טוֹב', transKu: 'tov (baş)', transEn: 'tov (good)' },
            { char: 'י', nameKu: 'Yod', nameEn: 'Yod', soundKu: 'y / î', soundEn: 'y / i', exHe: 'יוֹם', transKu: 'yom (roj)', transEn: 'yom (day)' },
            { char: 'כ/ך', nameKu: 'Kef', nameEn: 'Kaf / Khaf', soundKu: 'k / x', soundEn: 'k / x', exHe: 'כֶּלֶב', transKu: 'kelev (kûçik)', transEn: 'kelev (dog)' },
            { char: 'ל', nameKu: 'Lemed', nameEn: 'Lamed', soundKu: 'l', soundEn: 'l', exHe: 'לֵב', transKu: 'lev (dil)', transEn: 'lev (heart)' },
            { char: 'מ/ם', nameKu: 'Mêm', nameEn: 'Mem', soundKu: 'm', soundEn: 'm', exHe: 'מַיִם', transKu: 'mayim (av)', transEn: 'mayim (water)' },
            { char: 'נ/ן', nameKu: 'Nun', nameEn: 'Nun', soundKu: 'n', soundEn: 'n', exHe: 'נָהָר', transKu: 'nahar (çem)', transEn: 'nahar (river)' },
            { char: 'ס', nameKu: 'Semex', nameEn: 'Samekh', soundKu: 's', soundEn: 's', exHe: 'סֵפֶר', transKu: 'sefer (pirtûk)', transEn: 'sefer (book)' },
            { char: 'ע', nameKu: 'Eyn', nameEn: 'Ayin', soundKu: 'bêdeng / e / a', soundEn: 'silent / e / a', exHe: 'עֵץ', transKu: 'ets (dar)', transEn: 'ets (tree)' },
            { char: 'פ/ף', nameKu: 'Pê / Fê', nameEn: 'Pe / Fe', soundKu: 'p / f', soundEn: 'p / f', exHe: 'פֶּה', transKu: 'pe (dev)', transEn: 'pe (mouth)' },
            { char: 'צ/ץ', nameKu: 'Tsadî', nameEn: 'Tsadi', soundKu: 'ts', soundEn: 'ts', exHe: 'צִפּוֹר', transKu: 'tsipor (çivîk)', transEn: 'tsipor (bird)' },
            { char: 'ק', nameKu: 'Kof', nameEn: 'Qof', soundKu: 'k', soundEn: 'k', exHe: 'קוֹל', transKu: 'kol (deng)', transEn: 'kol (voice)' },
            { char: 'ר', nameKu: 'Rêş', nameEn: 'Resh', soundKu: 'r', soundEn: 'r', exHe: 'רֹאשׁ', transKu: 'roş (ser)', transEn: 'roş (head)' },
            { char: 'שׁ', nameKu: 'Şîn', nameEn: 'Shin', soundKu: 'ş', soundEn: 'sh', exHe: 'שָׁלוֹם', transKu: 'şalom (aştî)', transEn: 'shalom (peace)' },
            { char: 'שׂ', nameKu: 'Sîn', nameEn: 'Sin', soundKu: 's', soundEn: 's', exHe: 'שָׂרָה', transKu: 'Sara', transEn: 'Sarah' },
            { char: 'ת', nameKu: 'Tav', nameEn: 'Tav', soundKu: 't', soundEn: 't', exHe: 'תּוֹרָה', transKu: 'Torah (Tewrat)', transEn: 'Torah' }
        ];

        const nikudData = [
            { char: 'אָ / אַ', nameKu: 'Kamats / Patax', nameEn: 'Kamatz / Patach', soundKu: 'a', soundEn: 'a', exHe: 'אַבָּא', transKu: 'Aba (bav)', transEn: 'Aba (dad)' },
            { char: 'אֵ / אֶ', nameKu: 'Tsere / Segol', nameEn: 'Tzere / Segol', soundKu: 'e', soundEn: 'e', exHe: 'אֶרֶץ', transKu: 'Erets (welat)', transEn: 'Eretz (land)' },
            { char: 'אִ', nameKu: 'Xirik', nameEn: 'Chirik', soundKu: 'i', soundEn: 'i', exHe: 'אִמָּא', transKu: 'Ima (dê)', transEn: 'Ima (mom)' },
            { char: 'אֹ', nameKu: 'Xolam', nameEn: 'Cholam', soundKu: 'o', soundEn: 'o', exHe: 'אוֹר', transKu: 'Or (ronî)', transEn: 'Or (light)' },
            { char: 'אוּ', nameKu: 'Şûruk', nameEn: 'Shuruk', soundKu: 'u', soundEn: 'u', exHe: 'הוּא', transKu: 'Hu (ew)', transEn: 'Hu (he)' }
        ];

        const bes1WordsData = [
            { ku: 'Silavê / Aştî', en: 'Hello / Peace', he: 'שָׁלוֹם', trans: 'şalom', letters: ['ש', 'ל', 'ו', 'ם'] },
            { ku: 'Spas', en: 'Thank you', he: 'תּוֹדָה', trans: 'toda', letters: ['ת', 'ו', 'ד', 'ה'] },
            { ku: 'Erê', en: 'Yes', he: 'כֵּן', trans: 'ken', letters: ['כ', 'ן'] },
            { ku: 'Na', en: 'No', he: 'לֹא', trans: 'lo', letters: ['ל', 'א'] },
            { ku: 'Mal', en: 'House', he: 'בַּיִת', trans: 'bayit', letters: ['ב', 'י', 'ת'] },
            { ku: 'Av', en: 'Water', he: 'מַיִם', trans: 'mayim', letters: ['מ', 'י', 'ם'] },
            { ku: 'Roj', en: 'Day', he: 'יוֹם', trans: 'yom', letters: ['י', 'ו', 'ם'] },
            { ku: 'Pirtûk', en: 'Book', he: 'סֵפֶר', trans: 'sefer', letters: ['ס', 'פ', 'ר'] },
            { ku: 'Fêr bûn', en: 'To learn', he: 'לִלְמֹד', trans: 'lilmod', letters: ['ל', 'ל', 'מ', 'ד'] },
            { ku: 'Xwendin', en: 'To read', he: 'לִקְרֹא', trans: 'likro', letters: ['ל', 'ק', 'ר', 'א'] }
        ];

        const bes1SentencesData = [
            { ku: 'Silav, spas', en: 'Hello, thanks', words: ['שָׁלוֹם', 'תּוֹדָה'], trans: 'şalom, toda' },
            { ku: 'Erê, av', en: 'Yes, water', words: ['כֵּן', 'מַיִם'], trans: 'ken, mayim' },
            { ku: 'Xwendin pirtûk', en: 'Read a book', words: ['לִקְרֹא', 'סֵפֶר'], trans: 'likro sefer' },
            { ku: 'Mal, roj', en: 'House, day', words: ['בַּיִת', 'יוֹם'], trans: 'bayit, yom' },
            { ku: 'Na, spas', en: 'No, thanks', words: ['לֹא', 'תּוֹדָה'], trans: 'lo, toda' }
        ];

        const bes1HomeworkData = [
            { ku: "Tîpa 'ş' ya Îbranî (ש) di du awayan de tê xwendin. Wan binivîsin.", en: "The Hebrew letter 'ş' (ש) is read in two ways. Write them." },
            { ku: "Tîpên ku dengdêr (vokal) nîn in navên wan binivîsin.", en: "Write the names of the letters that do not have vowels." },
            { ku: "Peyvên jêrîn bi dengdêr (nikud) bixwînin: שָׁלוֹם, יוֹם, מַיִם, בַּיִת", en: "Read the following words with vowels (nikud): שָׁלוֹם, יוֹם, מַיִם, בַּיִת" },
            { ku: "Alfabeya Îbranî ji kîjan aliyî ber bi kîjan aliyî tê xwendin?", en: "From which direction is the Hebrew alphabet read?" },
            { ku: "Çend tîpên alfabeya Îbranî hene? Bi Îbranî û Kurmancî binivîsin.", en: "How many letters are in the Hebrew alphabet? Write it in Hebrew and Kurmanji." }
        ];

        const bes2DialogData = [
            { spkKu: 'Arya', spkEn: 'Arya', he: 'שָׁלוֹם! שְׁמִי אַרְיֵה.', trans: 'Şalom! Şmi Arye.', ku: 'Silavê! Navê min Arya ye.', en: 'Hello! My name is Arya.' },
            { spkKu: 'Dani', spkEn: 'Dani', he: 'שָׁלוֹם! שְׁמִי דָּנִי. מַה שְּׁלוֹמְךָ?', trans: 'Şalom! Şmi Dani. Ma şlomxa?', ku: 'Silavê! Navê min Dani ye. Tu çawa yî?', en: 'Hello! My name is Dani. How are you?' },
            { spkKu: 'Arya', spkEn: 'Arya', he: 'אֲנִי בְּסֵדֶר, תּוֹדָה. מֵאֵיפֹה אַתָּה?', trans: 'Ani bseder, toda. Meeyfo ata?', ku: 'Ez baş im, spas. Tu ji ku yî?', en: 'I am fine, thanks. Where are you from?' },
            { spkKu: 'Dani', spkEn: 'Dani', he: 'אֲנִי מִקּוּרְדִיסְטָן. מַה אַתָּה רוֹצֶה לַעֲשׂוֹת בָּאָרֶץ?', trans: "Ani mi'Kurdistan. Ma ata rotse la’asot ba’arets?", ku: 'Ez ji Kurdistanê me. Tu çi dixwazî li Îsraêlê bikî?', en: 'I am from Kurdistan. What do you want to do in Israel?' },
            { spkKu: 'Arya', spkEn: 'Arya', he: 'אֲנִי רוֹצֶה לִלְמֹד עִבְרִית.', trans: 'Ani rotse lilmod İvrit.', ku: 'Ez dixwazim Îbranî fêr bibim.', en: 'I want to learn Hebrew.' },
            { spkKu: 'Dani', spkEn: 'Dani', he: 'מְצוּיָּן! בָּרוּךְ הַבָּא.', trans: 'Mtsuyân! Barux haba.', ku: 'Baş e! Bi xêr hatî.', en: 'Excellent! Welcome.' },
            { spkKu: 'Arya', spkEn: 'Arya', he: 'בֶּן כַּמָּה אַתָּה?', trans: 'Ben kama ata?', ku: 'Çend salên te hene?', en: 'How old are you?' },
            { spkKu: 'Dani', spkEn: 'Dani', he: 'אֲנִי בֶּן עֶשְׂרִים וְשָׁלוֹשׁ. וְאַתָּה?', trans: "Ani ben esrim veşaloş. Ve'ata?", ku: 'Bîst û sê salên min hene. Tu?', en: 'I am twenty-three years old. And you?' },
            { spkKu: 'Arya', spkEn: 'Arya', he: 'אֲנִי בֶּן עֶשְׂרִים וְאֶחָד. אֵיפֹה אַתָּה גָּר?', trans: "Ani ben esrim ve'exad. Eyfo ata gar?", ku: 'Min bîst û yek salên min hene. Tu li ku dijî?', en: 'I am twenty-one years old. Where do you live?' },
            { spkKu: 'Dani', spkEn: 'Dani', he: 'אֲנִי גָּר בְּקוּרְדִיסְטָן. מְקַוֶּה שֶׁנִּיפָּגֵשׁ שׁוּב!', trans: 'Ani gar beKurdistan. Mekave şenipageş şuv!', ku: 'Ez li Kurdistanê dijim. Hêvî dikim em dîsa bibin hev!', en: 'I live in Kurdistan. I hope we meet again!' }
        ];

        const bes2WordsData = [
            { ku: 'silav', en: 'hello', he: 'שלום', trans: 'şalom' },
            { ku: 'nav', en: 'name', he: 'שֵׁם', trans: 'şem' },
            { ku: 'ez', en: 'I', he: 'אֲנִי', trans: 'anî' },
            { ku: 'tu', en: 'you', he: 'אַתָּה / אַתְּ', trans: 'ata / at' },
            { ku: 'baş', en: 'good', he: 'טוֹב', trans: 'tov' },
            { ku: 'spas', en: 'thank you', he: 'תּוֹדָה', trans: 'toda' },
            { ku: 'ji ku', en: 'from where', he: 'מֵאַיִן', trans: "me'ayin" },
            { ku: 'dixwazim', en: 'I want', he: 'אֲנִי רוֹצֶה', trans: 'anî rotse' },
            { ku: 'fêr bûn', en: 'to learn', he: 'לִלְמֹד', trans: 'lilmod' },
            { ku: 'bi xêr hatî', en: 'welcome', he: 'בָּרוּךְ הַבָּא', trans: 'barux haba' },
            { ku: 'erê', en: 'yes', he: 'כֵּן', trans: 'ken' },
            { ku: 'na', en: 'no', he: 'לֹא', trans: 'no' },
            { ku: 'xweş', en: 'pleasant', he: 'נָעִים', trans: 'naîm' },
            { ku: 'heval', en: 'friend', he: 'חָבֵר', trans: 'xaver' },
            { ku: 'şev', en: 'night', he: 'לַיְלָה', trans: 'layla' },
            { ku: 'roj', en: 'day', he: 'יוֹם', trans: 'yom' },
            { ku: 'sibeh', en: 'morning', he: 'בֹּקֶר', trans: 'boker' },
            { ku: 'êvar', en: 'evening', he: 'עֶרֶב', trans: 'erev' },
            { ku: 'zû', en: 'quickly', he: 'מַהֵר', trans: 'maher' },
            { ku: 'xwedahafiz', en: 'goodbye', he: 'לְהִתְרָאוֹת', trans: 'lehitraot' }
        ];

        const bes2GrammarData = [
            { ku: 'Ez', en: 'I', he: 'אֲנִי', noteKu: 'im', noteEn: 'am', pronHe: 'ani', cgForm: 'אֶהְיֶה', cgFormPron: 'ehye' },
            { ku: 'Tu', en: 'You', he: 'אַתָּה / אַתְּ', noteKu: 'yî', noteEn: 'are', pronHe: 'ata / at', cgForm: 'תִּהְיֶה / תִּהְיִי', cgFormPron: 'tihye / tihyi' },
            { ku: 'Ew (nêr)', en: 'He', he: 'הוּא', noteKu: 'e', noteEn: 'is', pronHe: 'hu', cgForm: 'יִהְיֶה', cgFormPron: 'yihye' },
            { ku: 'Ew (mê)', en: 'She', he: 'הִיא', noteKu: 'e', noteEn: 'is', pronHe: 'hi', cgForm: 'תִּהְיֶה', cgFormPron: 'tihye' },
            { ku: 'Em', en: 'We', he: 'אֲנַחְנוּ', noteKu: 'in', noteEn: 'are', pronHe: 'anaxnu', cgForm: 'נִהְיֶה', cgFormPron: 'nihye' },
            { ku: 'Hûn', en: 'You (plural)', he: 'אַתֶּם / אַתֶּן', noteKu: 'in', noteEn: 'are', pronHe: 'atem / aten', cgForm: 'תִּהְיוּ', cgFormPron: 'tihyu' },
            { ku: 'Ew (pirjimar)', en: 'They', he: 'הֵם / הֵן', noteKu: 'in', noteEn: 'are', pronHe: 'hem / hen', cgForm: 'יִהְיוּ', cgFormPron: 'yihyu' }
        ];

        const bes2HomeworkData = [
            { ku: 'Navê min Arya ye.', en: 'My name is Arya.' },
            { ku: 'Tu çawa yî?', en: 'How are you?' },
            { ku: 'Ez baş im.', en: 'I am fine.' },
            { ku: 'Spas ji bo alîkariyê.', en: 'Thank you for the help.' },
            { ku: 'Tu ji ku yî?', en: 'Where are you from?' },
            { ku: 'Bi xêr hatî!', en: 'Welcome!' },
            { ku: 'Heval baş e.', en: 'The friend is good.' },
            { ku: 'Sibehxêr!', en: 'Good morning!' },
            { ku: 'Êvarxêr!', en: 'Good evening!' },
            { ku: 'Xwedahafiz, heval.', en: 'Goodbye, friend.' }
        ];

        const bes2GameWordsData = [
            { ku: 'silav', en: 'hello', he: 'שלום', trans: 'şalom' },
            { ku: 'nav', en: 'name', he: 'שֵׁם', trans: 'şem' },
            { ku: 'ez', en: 'I', he: 'אֲנִי', trans: 'anî' },
            { ku: 'spas', en: 'thank you', he: 'תּוֹדָה', trans: 'toda' },
            { ku: 'ji ku', en: 'from where', he: 'מֵאַיִן', trans: "me'ayin" },
            { ku: 'fêr bûn', en: 'to learn', he: 'לִלְמֹד', trans: 'lilmod' },
            { ku: 'erê', en: 'yes', he: 'כֵּן', trans: 'ken' },
            { ku: 'na', en: 'no', he: 'לֹא', trans: 'no' },
            { ku: 'xweş', en: 'pleasant', he: 'נָעִים', trans: 'naîm' },
            { ku: 'heval', en: 'friend', he: 'חָבֵר', trans: 'xaver' },
            { ku: 'şev', en: 'night', he: 'לַיְלָה', trans: 'layla' },
            { ku: 'roj', en: 'day', he: 'יוֹם', trans: 'yom' },
            { ku: 'sibeh', en: 'morning', he: 'בֹּקֶר', trans: 'boker' },
            { ku: 'êvar', en: 'evening', he: 'עֶרֶב', trans: 'erev' },
            { ku: 'zû', en: 'quickly', he: 'מַהֵר', trans: 'maher' },
            { ku: 'xwedahafiz', en: 'goodbye', he: 'לְהִתְרָאוֹת', trans: 'lehitraot' },
            { ku: 'dixwazim', en: 'I want', he: 'אֲנִי רוֹצֶה', trans: 'anî rotse', speaker: 'masc' },
            { ku: 'dixwazim', en: 'I want', he: 'אֲנִי רוֹצָה', trans: 'anî rotsa', speaker: 'fem' },
            { ku: 'bi xêr hatî', en: 'welcome', he: 'בָּרוּךְ הַבָּא', trans: 'barux haba', speaker: 'masc' },
            { ku: 'bi xêr hatî', en: 'welcome', he: 'בְּרוּכָה הַבָּאָה', trans: "bruxa haba'a", speaker: 'fem' },
            { ku: 'ez dijim', en: 'I live', he: 'אֲנִי גָּר', trans: 'ani gar', speaker: 'masc' },
            { ku: 'ez dijim', en: 'I live', he: 'אֲנִי גָּרָה', trans: 'ani gara', speaker: 'fem' }
        ];

        const bes2GameSentencesData = [
            { ku: 'Silav heval', en: 'Hello, friend', words: ['שָׁלוֹם', 'חָבֵר'], trans: 'şalom xaver' },
            { ku: 'Ez baş im, spas', en: 'I am fine, thank you', words: ['אֲנִי', 'בְּסֵדֶר', 'תּוֹדָה'], trans: 'ani bseder, toda' },
            { ku: 'Ez dixwazim Îbranî fêr bibim.', en: 'I want to learn Hebrew.', words: ['אֲנִי', 'רוֹצֶה', 'לִלְמֹד', 'עִבְרִית'], trans: 'ani rotse lilmod ivrit', speaker: 'masc' },
            { ku: 'Ez dixwazim Îbranî fêr bibim.', en: 'I want to learn Hebrew.', words: ['אֲנִי', 'רוֹצָה', 'לִלְמֹד', 'עִבְרִית'], trans: 'ani rotsa lilmod ivrit', speaker: 'fem' },
            { ku: 'Bi xêr hatî!', en: 'Welcome!', words: ['בָּרוּךְ', 'הַבָּא'], trans: 'barux haba', speaker: 'masc' },
            { ku: 'Bi xêr hatî!', en: 'Welcome!', words: ['בְּרוּכָה', 'הַבָּאָה'], trans: "bruxa haba'a", speaker: 'fem' },
            { ku: 'Ez li Kurdistanê dijim.', en: 'I live in Kurdistan.', words: ['אֲנִי', 'גָּר', 'בְּקוּרְדִיסְטָן'], trans: 'ani gar beKurdistan', speaker: 'masc' },
            { ku: 'Ez li Kurdistanê dijim.', en: 'I live in Kurdistan.', words: ['אֲנִי', 'גָּרָה', 'בְּקוּרְדִיסְטָן'], trans: 'ani gara beKurdistan', speaker: 'fem' },
            { ku: 'Sibehxêr!', en: 'Good morning!', words: ['בֹּקֶר', 'טוֹב'], trans: 'boker tov' },
            { ku: 'Êvarxêr!', en: 'Good evening!', words: ['עֶרֶב', 'נָעִים'], trans: 'erev naîm' }
        ];
