/* The game's dictionary: every word spoken in the recordings, written as
   it is on the paper, with how to say it and its English meaning. Clicking
   a word on the paper shows both.

   "mean" is a list of lines, one meaning on each line and no brackets. A
   Dari phrase with the word gets a line of its own: the phrase, a colon,
   then its English, as in "به یاد داشتن: to remember".

   "say" spells the colloquial Kabul Dari sound in English letters, one
   hyphen between syllables: aa as in father, a as in cat, ay as in say,
   ee as in see, i as in sit, o as in go, oo as in food, u as in put,
   aw as in cow. kh is the rough h in Scottish loch, gh is a French r,
   q is a k made deep in the throat.

   Hand-edited: change a word here, then run python build/make_dictionary.py
   to refresh story_elements/dictionary.md and to list any spoken word that
   has no entry yet. */
var JINN_GLOSSARY = {
  "اتاق": {"say": "u-taaq", "mean": ["room"]},
  "اتاقش": {"say": "u-taa-qish", "mean": ["her room"]},
  "اتاقم": {"say": "u-taa-qum", "mean": ["my room"]},
  "اجازه": {"say": "i-jaa-za", "mean": ["permission", "اجازه داشتن: to be allowed"]},
  "احمد": {"say": "ah-mad", "mean": ["Ahmad, a name"]},
  "ارباب": {"say": "ar-baab", "mean": ["village head, the man who leads a village"]},
  "از": {"say": "az", "mean": ["from", "of", "than"]},
  "ازی": {"say": "a-zee", "mean": ["from this", "پیش ازی: before, before this"]},
  "است": {"say": "ast", "mean": ["is"]},
  "استم": {"say": "as-tum", "mean": ["I am"]},
  "استن": {"say": "as-tan", "mean": ["they are"]},
  "استین": {"say": "as-teen", "mean": ["you are, the polite form"]},
  "اضافه": {"say": "i-zaa-fa", "mean": ["extra, left over"]},
  "افتاد": {"say": "uf-taad", "mean": ["fell"]},
  "افغانی": {"say": "af-ghaa-nee", "mean": ["afghani, the Afghan money", "Afghan"]},
  "اکثراً": {"say": "ak-sa-ran", "mean": ["mostly, usually"]},
  "اگر": {"say": "a-gar", "mean": ["if"]},
  "البته": {"say": "al-bat-ta", "mean": ["of course"]},
  "امانت": {"say": "a-maa-nat", "mean": ["something left in your care"]},
  "امروز": {"say": "im-roz", "mean": ["today"]},
  "امسال": {"say": "im-saal", "mean": ["this year"]},
  "امشام": {"say": "im-shaam", "mean": ["this evening"]},
  "امشو": {"say": "im-shaw", "mean": ["tonight"]},
  "امصبح": {"say": "im-subh", "mean": ["this morning"]},
  "انداخت": {"say": "an-daakht", "mean": ["threw"]},
  "انداختم": {"say": "an-daakh-tum", "mean": ["I dropped, I threw"]},
  "او": {"say": "oo", "mean": ["he, she", "that"]},
  "اوقدر": {"say": "aw-qa-dar", "mean": ["so much, so"]},
  "اول": {"say": "aw-wal", "mean": ["first"]},
  "اولین": {"say": "aw-wa-leen", "mean": ["the first"]},
  "اونا": {"say": "oo-naa", "mean": ["they, them", "those"]},
  "اونجه": {"say": "oon-ja", "mean": ["there"]},
  "ای": {"say": "ee", "mean": ["this"]},
  "ایران": {"say": "ee-raan", "mean": ["Iran"]},
  "ایرانی": {"say": "ee-raa-nee", "mean": ["Iranian, from Iran"]},
  "ایستاد": {"say": "ees-taad", "mean": ["standing", "ایستاد شدن: to stand"]},
  "ایقه": {"say": "ee-qa", "mean": ["this much, so much"]},
  "ایماندار": {"say": "ee-maan-daar", "mean": ["honest"]},
  "ایماندارتر": {"say": "ee-maan-daar-tar", "mean": ["more honest"]},
  "اینجه": {"say": "een-ja", "mean": ["here"]},
  "آخر": {"say": "aa-khir", "mean": ["last", "the end"]},
  "آخرین": {"say": "aa-khi-reen", "mean": ["the last"]},
  "آدم": {"say": "aa-dam", "mean": ["person, human"]},
  "آدمی": {"say": "aa-da-mee", "mean": ["a man who, a person who"]},
  "آرام": {"say": "aa-raam", "mean": ["quiet, quietly", "calm"]},
  "آرد": {"say": "aard", "mean": ["flour"]},
  "آمد": {"say": "aa-mad", "mean": ["came"]},
  "آمدن": {"say": "aa-ma-dan", "mean": ["they came", "coming"]},
  "آو": {"say": "aaw", "mean": ["water"]},
  "آواز": {"say": "aa-waaz", "mean": ["voice", "sound"]},
  "آوازش": {"say": "aa-waa-zish", "mean": ["her voice, his voice"]},
  "آورد": {"say": "aa-ward", "mean": ["brought"]},
  "آوردم": {"say": "aa-war-dum", "mean": ["I brought", "به یاد آوردم: I remembered"]},
  "آهسته": {"say": "aa-his-ta", "mean": ["slowly, quietly"]},
  "بادنجان": {"say": "baa-din-jaan", "mean": ["aubergine", "بادنجان رومی: tomato"]},
  "باریک": {"say": "baa-reek", "mean": ["thin"]},
  "باز": {"say": "baaz", "mean": ["again"]},
  "بازی": {"say": "baa-zee", "mean": ["play, game", "بازی کدن: to play"]},
  "باشن": {"say": "baa-shan", "mean": ["that they are"]},
  "باشه": {"say": "baa-sha", "mean": ["that it is, may be"]},
  "باشین": {"say": "baa-sheen", "mean": ["be, the polite form", "چپ باشین: be quiet"]},
  "بالا": {"say": "baa-laa", "mean": ["up"]},
  "باور": {"say": "baa-war", "mean": ["belief", "باور کدن: to believe"]},
  "باید": {"say": "baa-yad", "mean": ["must, should"]},
  "ببخشین": {"say": "ba-bakh-sheen", "mean": ["sorry, excuse me"]},
  "ببرم": {"say": "bi-ba-rum", "mean": ["that I take"]},
  "ببینین": {"say": "bi-bee-nayn", "mean": ["see, the polite form for you"]},
  "بپاله": {"say": "bi-paa-la", "mean": ["that he looks for"]},
  "بپالین": {"say": "bi-paa-leen", "mean": ["look for, search, the polite form"]},
  "بتری": {"say": "bat-ree", "mean": ["battery"]},
  "بتری‌ها": {"say": "bat-ree-haa", "mean": ["batteries"]},
  "بتری‌های": {"say": "bat-ree-haa-yi", "mean": ["the batteries of"]},
  "بتری‌هایش": {"say": "bat-ree-haa-yish", "mean": ["his batteries"]},
  "بتم": {"say": "bi-tum", "mean": ["that I give"]},
  "بچشین": {"say": "bi-cha-sheen", "mean": ["taste, the polite form"]},
  "بچه": {"say": "ba-cha", "mean": ["son, boy", "child"]},
  "بچه‌ام": {"say": "ba-cha-um", "mean": ["my son"]},
  "بچه‌ها": {"say": "ba-cha-haa", "mean": ["boys, children"]},
  "بچه‌های": {"say": "ba-cha-haa-yi", "mean": ["the sons, the children of"]},
  "بچیم": {"say": "ba-chaym", "mean": ["my son, said to your son"]},
  "بخاطر": {"say": "ba-khaa-tir", "mean": ["because of"]},
  "بخاطری": {"say": "ba-khaa-ti-ray", "mean": ["because", "بخاطری که: because"]},
  "بخایم": {"say": "bi-khaa-yum", "mean": ["that I ask for", "معذرت بخایم: that I say sorry"]},
  "بخرم": {"say": "bi-kha-rum", "mean": ["that I buy"]},
  "بخره": {"say": "bi-kha-ra", "mean": ["that he buys"]},
  "بخورین": {"say": "bi-kho-reen", "mean": ["eat, drink, the polite form"]},
  "بخیر": {"say": "ba-khayr", "mean": ["well", "شو بخیر: good night"]},
  "بد": {"say": "bad", "mean": ["bad"]},
  "بدل": {"say": "ba-dal", "mean": ["changed", "بدل کدن: to change"]},
  "بدی": {"say": "ba-dee", "mean": ["harm, something bad"]},
  "برادرم": {"say": "ba-raa-da-rum", "mean": ["my brother"]},
  "برایش": {"say": "ba-raa-yish", "mean": ["for him/her", "to him/her"]},
  "برایم": {"say": "ba-raa-yum", "mean": ["to me, for me"]},
  "بردم": {"say": "bur-dum", "mean": ["I took, I carried"]},
  "برف": {"say": "barf", "mean": ["snow"]},
  "برم": {"say": "bu-rum", "mean": ["that I go"]},
  "برنج": {"say": "bi-rinj", "mean": ["rice"]},
  "بری": {"say": "ba-ray", "mean": ["for"]},
  "برین": {"say": "ba-reen", "mean": ["go, the polite form"]},
  "بزغاله": {"say": "buz-ghaa-la", "mean": ["a baby goat"]},
  "بزنه": {"say": "bi-za-na", "mean": ["that he hits", "گپ بزنه: that he talks"]},
  "بزنین": {"say": "bi-za-neen", "mean": ["hit, the polite form", "گپ بزنین: talk"]},
  "بسته": {"say": "bas-ta", "mean": ["closed, shut"]},
  "بسیار": {"say": "bis-yaar", "mean": ["very, much", "a lot"]},
  "بشکنم": {"say": "bi-shi-ka-num", "mean": ["that I break"]},
  "بشینین": {"say": "bi-shee-neen", "mean": ["sit down, the polite form"]},
  "بعد": {"say": "baad", "mean": ["after", "then, later"]},
  "بعدی": {"say": "ba-dee", "mean": ["next"]},
  "بفرمایین": {"say": "bi-far-maa-yeen", "mean": ["please, help yourself"]},
  "بگم": {"say": "bu-gum", "mean": ["that I say"]},
  "بگیره": {"say": "bi-gee-ra", "mean": ["that he takes"]},
  "بگین": {"say": "bu-geen", "mean": ["say, tell, the polite form", "راست بگین: tell the truth"]},
  "بلی": {"say": "ba-lay", "mean": ["yes"]},
  "بمانه": {"say": "bi-maa-na", "mean": ["that he/she puts", "that he/she stays"]},
  "بنویسه": {"say": "bi-na-wee-sa", "mean": ["that he or she writes"]},
  "بوت‌های": {"say": "boot-haay", "mean": ["the shoes, the boots of"]},
  "بوجی": {"say": "bo-jee", "mean": ["sack, a big cloth bag"]},
  "بوجی‌ها": {"say": "bo-jee-haa", "mean": ["sacks"]},
  "بوجی‌های": {"say": "bo-jee-haa-yi", "mean": ["the sacks of"]},
  "بود": {"say": "bood", "mean": ["was"]},
  "بودم": {"say": "boo-dum", "mean": ["I was"]},
  "بودن": {"say": "boo-dan", "mean": ["they were"]},
  "بوره": {"say": "boo-ra", "mean": ["sugar"]},
  "بوی": {"say": "boo-yi", "mean": ["the smell of"]},
  "به": {"say": "ba", "mean": ["to"]},
  "بهار": {"say": "ba-haar", "mean": ["spring, the season"]},
  "بهتر": {"say": "bih-tar", "mean": ["better"]},
  "بهترین": {"say": "bih-ta-reen", "mean": ["the best"]},
  "بی": {"say": "bay", "mean": ["without"]},
  "بیارم": {"say": "bi-yaa-rum", "mean": ["that I bring"]},
  "بیارین": {"say": "bi-yaa-reen", "mean": ["bring, the polite form"]},
  "بیاین": {"say": "bi-yaa-yeen", "mean": ["come, the polite form"]},
  "بی‌بی‌سی": {"say": "bee-bee-see", "mean": ["the BBC, the radio news from London"]},
  "بیچاره": {"say": "bay-chaa-ra", "mean": ["poor thing"]},
  "بیرون": {"say": "bay-roon", "mean": ["outside, out"]},
  "بیست": {"say": "beest", "mean": ["twenty"]},
  "بینی": {"say": "bee-nee", "mean": ["nose"]},
  "پارسال": {"say": "paar-saal", "mean": ["last year"]},
  "پایان": {"say": "paa-yaan", "mean": ["down"]},
  "پختن": {"say": "pukh-tan", "mean": ["baking"]},
  "پخته": {"say": "pukh-ta", "mean": ["cooked, baked", "پخته کدن: to bake"]},
  "پدر": {"say": "pa-dar", "mean": ["father"]},
  "پدرش": {"say": "pa-da-rish", "mean": ["his/her father"]},
  "پدرکلانم": {"say": "pi-dar-ka-laa-num", "mean": ["my grandfather"]},
  "پدرم": {"say": "pa-da-rum", "mean": ["my father"]},
  "پر": {"say": "pur", "mean": ["full", "filled"]},
  "پرسان": {"say": "pur-saan", "mean": ["asking", "پرسان کدن: to ask"]},
  "پروین": {"say": "par-ween", "mean": ["Parwin, a name"]},
  "پس": {"say": "pas", "mean": ["back again", "so, then", "behind"]},
  "پشک": {"say": "pi-shak", "mean": ["cat"]},
  "پشیمان": {"say": "pa-shay-maan", "mean": ["sorry, regretful"]},
  "پلو": {"say": "pa-loo", "mean": ["beside, next to", "pulao, rice cooked with raisins or meat"]},
  "پلوی": {"say": "pa-loo-yi", "mean": ["next to, beside", "the pulao of, the rice dish of"]},
  "پلویش": {"say": "pa-loo-yish", "mean": ["next to her, beside him"]},
  "پنج": {"say": "panj", "mean": ["five"]},
  "پنجشنبه": {"say": "panj-sham-ba", "mean": ["Thursday"]},
  "پهلوی": {"say": "pah-loo-yi", "mean": ["next to, beside"]},
  "پیاده": {"say": "pi-yaa-da", "mean": ["on foot", "پیاده رفتن: to walk off, to go on foot"]},
  "پیاز": {"say": "pee-yaaz", "mean": ["onion"]},
  "پیاله": {"say": "pi-yaa-la", "mean": ["cup, a small tea bowl"]},
  "پیاله‌ها": {"say": "pi-yaa-la-haa", "mean": ["the cups"]},
  "پیدا": {"say": "pay-daa", "mean": ["found", "پیدا کدن: to find"]},
  "پیدایش": {"say": "pay-daa-yish", "mean": ["find it", "پیدایش می‌کنم: I will find it"]},
  "پیر": {"say": "peer", "mean": ["old, of people"]},
  "پیراهن": {"say": "pay-raa-han", "mean": ["shirt, tunic"]},
  "پیسه": {"say": "pay-sa", "mean": ["money"]},
  "پیسه‌اش": {"say": "pay-sa-ash", "mean": ["its money, the money for it"]},
  "پیسه‌های": {"say": "pay-sa-haa-yi", "mean": ["the money of"]},
  "پیش": {"say": "paysh", "mean": ["before", "near, at someone's place"]},
  "تا": {"say": "taa", "mean": ["until", "so that"]},
  "تار": {"say": "taar", "mean": ["string, thread"]},
  "تازه": {"say": "taa-za", "mean": ["fresh", "just now"]},
  "تخم": {"say": "tukhm", "mean": ["egg, eggs"]},
  "ترس": {"say": "tars", "mean": ["fear"]},
  "ترسیدم": {"say": "tar-see-dum", "mean": ["I was afraid"]},
  "تشناب": {"say": "tash-naab", "mean": ["toilet, washroom"]},
  "تقلید": {"say": "taq-leed", "mean": ["copying someone", "تقلید کدن: to copy a voice, to imitate"]},
  "تمام": {"say": "ta-maam", "mean": ["all, the whole"]},
  "تنگ": {"say": "tang", "mean": ["tight, narrow", "دلم تنگ شده: I miss someone"]},
  "تنور": {"say": "ta-noor", "mean": ["tandur, a clay bread oven"]},
  "تنها": {"say": "tan-haa", "mean": ["alone"]},
  "تیز": {"say": "tayz", "mean": ["quickly, fast"]},
  "تیل": {"say": "tayl", "mean": ["oil, lamp oil"]},
  "جارو": {"say": "jaa-roo", "mean": ["broom", "جارو کدن: to sweep"]},
  "جان": {"say": "jaan", "mean": ["dear, said after a name", "life"]},
  "جای": {"say": "jaa-yi", "mean": ["place", "جای خواب: bed"]},
  "جمعه": {"say": "ju-ma", "mean": ["Friday"]},
  "جن": {"say": "jin", "mean": ["jinn, a spirit"]},
  "جنس": {"say": "jins", "mean": ["goods, things for sale"]},
  "جنس‌ها": {"say": "jins-haa", "mean": ["the goods"]},
  "جنس‌های": {"say": "jins-haa-yi", "mean": ["the goods of"]},
  "جنگ": {"say": "jang", "mean": ["war"]},
  "جواب": {"say": "ja-waab", "mean": ["answer"]},
  "جواد": {"say": "ja-waad", "mean": ["Jawad, a name"]},
  "جوان": {"say": "ja-waan", "mean": ["young"]},
  "جور": {"say": "jor", "mean": ["built, made", "fine, sound", "جور کدن: to build"]},
  "جوش": {"say": "josh", "mean": ["boiling", "جوش دادن: to boil, to brew"]},
  "جوی": {"say": "jooy", "mean": ["canal, irrigation channel"]},
  "جیب": {"say": "jayb", "mean": ["pocket"]},
  "چارده": {"say": "chaar-da", "mean": ["fourteen"]},
  "چارشنبه": {"say": "chaar-sham-ba", "mean": ["Wednesday"]},
  "چای": {"say": "chaay", "mean": ["tea"]},
  "چای‌خانه": {"say": "chaay-khaa-na", "mean": ["teahouse"]},
  "چپ": {"say": "chup", "mean": ["quiet, silent"]},
  "چرا": {"say": "chi-raa", "mean": ["why"]},
  "چراغ": {"say": "chi-raagh", "mean": ["lamp", "چراغ دستی: torch, flashlight"]},
  "چشم‌های": {"say": "chashm-haa-yi", "mean": ["the eyes of"]},
  "چشم‌هایش": {"say": "chashm-haa-yish", "mean": ["her eyes, his eyes"]},
  "چشم‌هایم": {"say": "chashm-haa-yum", "mean": ["my eyes"]},
  "چطور": {"say": "chi-tawr", "mean": ["how"]},
  "چهل": {"say": "chil", "mean": ["forty"]},
  "چی": {"say": "chee", "mean": ["what"]},
  "چیز": {"say": "cheez", "mean": ["thing"]},
  "چیزی": {"say": "chee-zay", "mean": ["something, anything"]},
  "چیغ": {"say": "cheegh", "mean": ["shout, scream", "چیغ زدن: to shout"]},
  "حالا": {"say": "haa-laa", "mean": ["now"]},
  "حتی": {"say": "hat-taa", "mean": ["even"]},
  "حساب": {"say": "hi-saab", "mean": ["counting, accounts", "حساب کدن: to count", "کتابچه حساب: account book"]},
  "حسابش": {"say": "hi-saa-bish", "mean": ["his accounts"]},
  "حمید": {"say": "ha-meed", "mean": ["Hamid, a name"]},
  "حویلی": {"say": "haw-lee", "mean": ["courtyard"]},
  "خاله": {"say": "khaa-la", "mean": ["aunt, mother's sister"]},
  "خاله‌اش": {"say": "khaa-la-ash", "mean": ["her aunt"]},
  "خالی": {"say": "khaa-lee", "mean": ["empty"]},
  "خالی‌تر": {"say": "khaa-lee-tar", "mean": ["emptier"]},
  "خانم": {"say": "khaa-num", "mean": ["wife of"]},
  "خانمم": {"say": "khaa-nu-mum", "mean": ["my wife"]},
  "خانه": {"say": "khaa-na", "mean": ["house, home"]},
  "خبر": {"say": "kha-bar", "mean": ["news", "خبر شدن: to hear about, to learn"]},
  "خبرهای": {"say": "kha-bar-haa-yi", "mean": ["the news of", "خبرهای بی‌بی‌سی: the BBC news"]},
  "خدا": {"say": "khu-daa", "mean": ["God", "به خدا: by God, I swear"]},
  "خدایا": {"say": "khu-daa-yaa", "mean": ["O God"]},
  "خر": {"say": "khar", "mean": ["donkey"]},
  "خراب": {"say": "kha-raab", "mean": ["bad, broken"]},
  "خرچ": {"say": "kharch", "mean": ["spending", "خرچ کدن: to spend"]},
  "خرخر": {"say": "khur-khur", "mean": ["snoring", "خرخر کدن: to snore"]},
  "خرخری": {"say": "khur-khu-ree", "mean": ["a snorer"]},
  "خرد": {"say": "khurd", "mean": ["small, little", "young"]},
  "خروس": {"say": "khu-roos", "mean": ["rooster"]},
  "خریدم": {"say": "kha-ree-dum", "mean": ["I bought"]},
  "خزان": {"say": "kha-zaan", "mean": ["autumn"]},
  "خشک": {"say": "khushk", "mean": ["dry, dried"]},
  "خشن": {"say": "kha-shin", "mean": ["rough"]},
  "خط": {"say": "khat", "mean": ["letter", "handwriting"]},
  "خنده": {"say": "khan-da", "mean": ["laughter", "خنده کدن: to laugh"]},
  "خنده‌دار": {"say": "khan-da-daar", "mean": ["funny"]},
  "خو": {"say": "kho (sleep: khaw)", "mean": ["but", "sleep", "خو کدن: to sleep", "خو دیدن: to dream"]},
  "خواب": {"say": "khaab", "mean": ["sleep", "جای خواب: bed"]},
  "خواستم": {"say": "khaas-tum", "mean": ["I asked for, I wanted"]},
  "خواند": {"say": "khaand", "mean": ["read, read aloud"]},
  "خواندم": {"say": "khaan-dum", "mean": ["I read aloud", "I prayed"]},
  "خوانده": {"say": "khaan-da", "mean": ["read", "خوانده نمی‌تانم: I can't read"]},
  "خواهر": {"say": "khaa-har", "mean": ["sister"]},
  "خواهرم": {"say": "khaa-ha-rum", "mean": ["my sister"]},
  "خوب": {"say": "khoob", "mean": ["good", "well"]},
  "خوبتر": {"say": "khoob-tar", "mean": ["better"]},
  "خود": {"say": "khud", "mean": ["own", "self"]},
  "خودش": {"say": "khu-dish", "mean": ["himself, herself"]},
  "خودشان": {"say": "khu-di-shaan", "mean": ["themselves"]},
  "خودم": {"say": "khu-dum", "mean": ["myself"]},
  "خورد": {"say": "khord", "mean": ["ate, drank"]},
  "خوردم": {"say": "khor-dum", "mean": ["I ate, I drank"]},
  "خوردن": {"say": "khor-dan", "mean": ["eating"]},
  "خورده": {"say": "khor-da", "mean": ["eaten", "خورده نمی‌تانم: I can't eat"]},
  "خوردیم": {"say": "khor-deem", "mean": ["we ate"]},
  "خوش": {"say": "khush", "mean": ["happy, pleased", "خوش داشتن: to like"]},
  "خوش‌بختی": {"say": "khosh-bakh-tee", "mean": ["good luck"]},
  "داخل": {"say": "daa-khil", "mean": ["inside"]},
  "داخلش": {"say": "daa-khi-lish", "mean": ["inside it"]},
  "داد": {"say": "daad", "mean": ["gave"]},
  "دادم": {"say": "daa-dum", "mean": ["I gave"]},
  "دادن": {"say": "daa-dan", "mean": ["they gave"]},
  "دارم": {"say": "daa-rum", "mean": ["I have"]},
  "داره": {"say": "daa-ra", "mean": ["has"]},
  "داشت": {"say": "daasht", "mean": ["had"]},
  "داشتن": {"say": "daash-tan", "mean": ["they had"]},
  "داغ": {"say": "daagh", "mean": ["hot"]},
  "دانه": {"say": "daa-na", "mean": ["grain, seed"]},
  "دختر": {"say": "dukh-tar", "mean": ["girl, daughter"]},
  "دخترا": {"say": "dukh-ta-raa", "mean": ["girls"]},
  "دخترک": {"say": "dukh-ta-rak", "mean": ["little girl"]},
  "دخترم": {"say": "dukh-ta-rum", "mean": ["my daughter"]},
  "درباره": {"say": "dar-baa-ra", "mean": ["about"]},
  "درباره‌اش": {"say": "dar-baa-ra-ash", "mean": ["about it, about him"]},
  "درد": {"say": "dard", "mean": ["pain", "درد کدن: to hurt"]},
  "دردسر": {"say": "dard-sar", "mean": ["trouble"]},
  "درست": {"say": "du-rust", "mean": ["right, correct"]},
  "دروازه": {"say": "dar-waa-za", "mean": ["gate, door"]},
  "دروازه‌اش": {"say": "dar-waa-za-ash", "mean": ["her door"]},
  "دروغ": {"say": "du-rogh", "mean": ["lie, a lie", "دروغ گفتن: to lie"]},
  "دروغگو": {"say": "du-rogh-go", "mean": ["liar"]},
  "دروغگوها": {"say": "du-rogh-go-haa", "mean": ["liars"]},
  "دریا": {"say": "dar-yaa", "mean": ["river"]},
  "دزدها": {"say": "duzd-haa", "mean": ["thieves"]},
  "دزدی": {"say": "duz-dee", "mean": ["stealing", "دزدی کدن: to steal"]},
  "دست": {"say": "dast", "mean": ["hand"]},
  "دسترخوان": {"say": "das-tar-khaan", "mean": ["the cloth spread on the floor for meals"]},
  "دست‌های": {"say": "dast-haa-yi", "mean": ["the hands of"]},
  "دست‌هایم": {"say": "dast-haa-yum", "mean": ["my hands"]},
  "دستی": {"say": "das-tee", "mean": ["for the hand", "چراغ دستی: torch, flashlight"]},
  "دفعه": {"say": "daf-a", "mean": ["time, occasion", "سه دفعه: three times"]},
  "دقیقه": {"say": "da-qee-qa", "mean": ["minute"]},
  "دکان": {"say": "du-kaan", "mean": ["shop"]},
  "دکاندار": {"say": "du-kaan-daar", "mean": ["shopkeeper"]},
  "دگه": {"say": "di-ga", "mean": ["other", "more", "any more", "دگه نه: no longer"]},
  "دلش": {"say": "di-lish", "mean": ["her heart", "دلش است: she wants"]},
  "دلم": {"say": "di-lum", "mean": ["my heart", "دلم تنگ شده: I miss someone"]},
  "دنیا": {"say": "dun-yaa", "mean": ["the world"]},
  "دو": {"say": "du", "mean": ["two"]},
  "دوازده": {"say": "du-waaz-da", "mean": ["twelve"]},
  "دوچند": {"say": "du-chand", "mean": ["double"]},
  "دور": {"say": "door", "mean": ["far, away"]},
  "دوست": {"say": "dost", "mean": ["friend", "دوست داشتن: to love, to like"]},
  "دوستایم": {"say": "dos-taa-yum", "mean": ["my friends"]},
  "دوید": {"say": "da-weed", "mean": ["ran"]},
  "ده": {"say": "da", "mean": ["in, at, into"]},
  "دهن": {"say": "da-han", "mean": ["mouth"]},
  "دهنم": {"say": "da-ha-num", "mean": ["my mouth"]},
  "دیدم": {"say": "dee-dum", "mean": ["I saw"]},
  "دیدن": {"say": "dee-dan", "mean": ["they saw", "seeing"]},
  "دیده": {"say": "dee-da", "mean": ["has seen, had seen"]},
  "دیروز": {"say": "day-roz", "mean": ["yesterday"]},
  "دیشو": {"say": "day-shaw", "mean": ["last night"]},
  "دیوار": {"say": "day-waar", "mean": ["wall"]},
  "دیوانه": {"say": "day-waa-na", "mean": ["mad, out of her mind"]},
  "دیوانه‌ها": {"say": "day-waa-na-haa", "mean": ["madmen, crazy people"]},
  "رادیو": {"say": "raa-dee-yo", "mean": ["radio"]},
  "رادیوی": {"say": "raa-dee-yo-yi", "mean": ["the radio of"]},
  "رادیویش": {"say": "raa-dee-yo-yish", "mean": ["his radio"]},
  "رادیویی": {"say": "raa-dee-yo-yee", "mean": ["a radio that"]},
  "رازهای": {"say": "raaz-haay", "mean": ["the secrets of"]},
  "رازی": {"say": "raa-zee", "mean": ["a secret, any secret"]},
  "راست": {"say": "raast", "mean": ["true"]},
  "رحم": {"say": "rahm", "mean": ["mercy", "رحم کدن: to have mercy"]},
  "رفت": {"say": "raft", "mean": ["went"]},
  "رفتم": {"say": "raf-tum", "mean": ["I went"]},
  "رفتن": {"say": "raf-tan", "mean": ["they went", "going"]},
  "رفته": {"say": "raf-ta", "mean": ["gone", "رفته نمی‌تانست: couldn't go"]},
  "رقم": {"say": "ra-qam", "mean": ["kind, type", "ای رقم: this kind of"]},
  "رقیه": {"say": "ru-qee-ya", "mean": ["Roqia, a name"]},
  "روان": {"say": "ra-waan", "mean": ["sent off, going", "روان کدن: to send"]},
  "روز": {"say": "roz", "mean": ["day"]},
  "روزی": {"say": "ro-zee", "mean": ["a day, per day", "روزی دوازده ساعت: twelve hours a day"]},
  "روشن": {"say": "raw-shan", "mean": ["lit, on, of a lamp"]},
  "روشنی": {"say": "raw-sha-nee", "mean": ["light"]},
  "رومی": {"say": "roo-mee", "mean": ["Roman", "بادنجان رومی: tomato"]},
  "روی": {"say": "roo-yi", "mean": ["face", "on"]},
  "ره": {"say": "ra", "mean": ["marks the object of a verb", "there is no English word for it"]},
  "ریش‌سفیدا": {"say": "reesh-sa-fay-daa", "mean": ["the elders, the old men who decide for the village"]},
  "زد": {"say": "zad", "mean": ["hit", "چیغ زد: shouted"]},
  "زدم": {"say": "za-dum", "mean": ["I hit", "چیغ زدم: I shouted"]},
  "زدن": {"say": "za-dan", "mean": ["hitting", "گپ زدن: talking"]},
  "زده": {"say": "za-da", "mean": ["hit", "صدمه زده نمی‌تانه: can't hurt"]},
  "زمستان": {"say": "zi-mis-taan", "mean": ["winter"]},
  "زن": {"say": "zan", "mean": ["woman", "wife"]},
  "زندگی": {"say": "zin-da-gee", "mean": ["life", "زندگی کدن: to live"]},
  "زن‌ها": {"say": "zan-haa", "mean": ["women"]},
  "زود": {"say": "zood", "mean": ["early, quickly"]},
  "زیاد": {"say": "zi-yaad", "mean": ["a lot, much, many"]},
  "زیادتر": {"say": "zi-yaad-tar", "mean": ["more"]},
  "زیر": {"say": "zayr", "mean": ["under"]},
  "ساعت": {"say": "saa-at", "mean": ["watch, clock", "hour", "ساعت نه: nine o'clock"]},
  "سال": {"say": "saal", "mean": ["year"]},
  "ساله": {"say": "saa-la", "mean": ["years old", "چارده ساله: fourteen years old"]},
  "سال‌ها": {"say": "saal-haa", "mean": ["years"]},
  "سبز": {"say": "sabz", "mean": ["green", "سبز شدن: to grow"]},
  "سخت‌ترین": {"say": "sakht-ta-reen", "mean": ["the hardest"]},
  "سر": {"say": "sar", "mean": ["head", "on, on top of", "at"]},
  "سرخ": {"say": "surkh", "mean": ["red"]},
  "سرد": {"say": "sard", "mean": ["cold"]},
  "سردی": {"say": "sar-dee", "mean": ["the cold"]},
  "سرش": {"say": "sa-rish", "mean": ["on it, over it"]},
  "سرک": {"say": "sa-rak", "mean": ["road"]},
  "سرم": {"say": "sa-rum", "mean": ["my head"]},
  "سفید": {"say": "sa-fayd", "mean": ["white"]},
  "سگ": {"say": "sag", "mean": ["dog"]},
  "سماوار": {"say": "sa-maa-waar", "mean": ["samovar, a big metal pot for boiling tea water"]},
  "سمیع": {"say": "sa-mee", "mean": ["Sami, a name"]},
  "سنگ": {"say": "sang", "mean": ["stone"]},
  "سوار": {"say": "sa-waar", "mean": ["riding", "سوار موتر: by car"]},
  "سودا": {"say": "saw-daa", "mean": ["trade, selling", "سودا کدن: to sell"]},
  "سوراخ": {"say": "soo-raakh", "mean": ["hole"]},
  "سه": {"say": "say", "mean": ["three"]},
  "سی": {"say": "see", "mean": ["thirty"]},
  "سیاه": {"say": "si-yaa", "mean": ["black"]},
  "سیل": {"say": "sayl", "mean": ["look", "سیل کدن: to look, to watch"]},
  "شاگرد": {"say": "shaa-gird", "mean": ["student, pupil"]},
  "شاگردش": {"say": "shaa-gir-dish", "mean": ["its student, her student"]},
  "شام": {"say": "shaam", "mean": ["evening"]},
  "شان": {"say": "shaan", "mean": ["their", "خود شان: their own"]},
  "شانزده": {"say": "shaanz-da", "mean": ["sixteen"]},
  "شاید": {"say": "shaa-yad", "mean": ["maybe, perhaps"]},
  "شپلاق": {"say": "shpi-laaq", "mean": ["whistle"]},
  "شجاع‌تر": {"say": "shu-jaa-tar", "mean": ["braver"]},
  "شد": {"say": "shud", "mean": ["became", "happened", "started"]},
  "شدم": {"say": "shu-dum", "mean": ["I became"]},
  "شده": {"say": "shu-da", "mean": ["has become", "had been"]},
  "شرم": {"say": "sharm", "mean": ["shame"]},
  "شروع": {"say": "shu-roo", "mean": ["start", "شروع کدن: to begin"]},
  "شستم": {"say": "shus-tum", "mean": ["I washed"]},
  "شصت": {"say": "shast", "mean": ["sixty"]},
  "شکر": {"say": "shukr", "mean": ["thanks", "شکر خدا: thank God"]},
  "شکست": {"say": "shi-kast", "mean": ["broke"]},
  "شما": {"say": "shu-maa", "mean": ["you, the polite form"]},
  "شنیدم": {"say": "shu-nee-dum", "mean": ["I heard"]},
  "شنیدن": {"say": "shu-nee-dan", "mean": ["they heard", "hearing"]},
  "شنیده": {"say": "shu-nee-da", "mean": ["had heard"]},
  "شو": {"say": "shaw", "mean": ["night", "کاکای شو: Uncle Night, the voice on the radio"]},
  "شوا": {"say": "sha-waa", "mean": ["at night, nights"]},
  "شوخی": {"say": "shokh-ee", "mean": ["joke", "شوخی کدن: to joke"]},
  "شوخی‌ها": {"say": "shokh-ee-haa", "mean": ["jokes"]},
  "شوخی‌های": {"say": "shokh-ee-haa-yi", "mean": ["the jokes of"]},
  "شوخی‌هایش": {"say": "shokh-ee-haa-yish", "mean": ["his jokes"]},
  "شوخی‌هایم": {"say": "shokh-ee-haa-yum", "mean": ["my jokes"]},
  "شوروا": {"say": "shor-waa", "mean": ["soup"]},
  "شوروای": {"say": "shor-waa-yi", "mean": ["the soup of", "شوروای گوشت: meat soup"]},
  "شوهای": {"say": "shaw-haa-yi", "mean": ["the nights of"]},
  "شوهر": {"say": "shaw-har", "mean": ["husband"]},
  "شوهرش": {"say": "shaw-ha-rish", "mean": ["her husband"]},
  "شوهرم": {"say": "shaw-ha-rum", "mean": ["my husband"]},
  "شیرین": {"say": "shee-reen", "mean": ["Shirin, a name"]},
  "شیرین‌تر": {"say": "shee-reen-tar", "mean": ["sweeter"]},
  "شیشتم": {"say": "shish-tum", "mean": ["I sat"]},
  "شیشته": {"say": "shish-ta", "mean": ["sitting", "شیشته بودم: I was sitting"]},
  "صابون": {"say": "saa-boon", "mean": ["soap"]},
  "صبا": {"say": "sa-baa", "mean": ["tomorrow"]},
  "صبح": {"say": "subh", "mean": ["morning"]},
  "صبحش": {"say": "sub-hish", "mean": ["the next morning"]},
  "صبر": {"say": "sabr", "mean": ["patience, waiting", "صبر کدن: to wait"]},
  "صد": {"say": "sad", "mean": ["a hundred"]},
  "صدا": {"say": "sa-daa", "mean": ["voice, sound", "صدا کدن: to call"]},
  "صفحه": {"say": "saf-ha", "mean": ["page"]},
  "صندلی": {"say": "san-da-lee", "mean": ["sandali, a low table over a heater, under blankets, where the family sits in winter"]},
  "صندوق": {"say": "san-dooq", "mean": ["trunk, a big box with a lid"]},
  "صنف": {"say": "sinf", "mean": ["class, a school class", "صنف دخترا: the girls' class"]},
  "طرف": {"say": "ta-raf", "mean": ["toward", "side"]},
  "عجیب": {"say": "a-jeeb", "mean": ["strange"]},
  "عدد": {"say": "a-dad", "mean": ["number"]},
  "عروسی": {"say": "a-roo-see", "mean": ["wedding", "عروسی کدن: to marry"]},
  "عزیز": {"say": "a-zeez", "mean": ["Aziz, a name", "dear"]},
  "عسل": {"say": "a-sal", "mean": ["honey"]},
  "عمر": {"say": "umr", "mean": ["life, a lifetime"]},
  "غذای": {"say": "gha-zaa-yi", "mean": ["the food of", "غذای خوش: favourite food"]},
  "غلط": {"say": "gha-lat", "mean": ["wrong, a mistake"]},
  "غلطی": {"say": "gha-la-tee", "mean": ["mistake"]},
  "غم": {"say": "gham", "mean": ["sorrow, worry"]},
  "غیر": {"say": "ghayr", "mean": ["other", "غیر از: except"]},
  "فابریکه": {"say": "faab-ree-ka", "mean": ["factory"]},
  "فامیدم": {"say": "faa-mee-dum", "mean": ["I found out, I understood"]},
  "فامیده": {"say": "faa-mee-da", "mean": ["has found out, has learned"]},
  "فامیل": {"say": "faa-meel", "mean": ["family"]},
  "فامیل‌ها": {"say": "faa-meel-haa", "mean": ["families"]},
  "فروخت": {"say": "fu-rokht", "mean": ["sold"]},
  "فروختم": {"say": "fu-rokh-tum", "mean": ["I sold"]},
  "فروختن": {"say": "fu-rokh-tan", "mean": ["selling"]},
  "فروخته": {"say": "fu-rokh-ta", "mean": ["has sold"]},
  "فقط": {"say": "fa-qat", "mean": ["only"]},
  "فکر": {"say": "fikr", "mean": ["thought", "فکر کدن: to think"]},
  "قار": {"say": "qaar", "mean": ["angry"]},
  "قاشق": {"say": "qaa-shuq", "mean": ["spoon"]},
  "قدم": {"say": "qa-dam", "mean": ["step", "قدم زدن: to walk"]},
  "قرض": {"say": "qarz", "mean": ["a loan", "قرض دادن: to lend"]},
  "قریه": {"say": "qar-ya", "mean": ["village"]},
  "قسم": {"say": "qa-sam", "mean": ["oath", "قسم خوردن: to swear"]},
  "قصه": {"say": "qis-sa", "mean": ["story"]},
  "قصه‌ها": {"say": "qis-sa-haa", "mean": ["stories"]},
  "قطی‌ها": {"say": "qu-tee-haa", "mean": ["boxes"]},
  "قلف": {"say": "qulf", "mean": ["lock", "قلف کدن: to lock"]},
  "قوی": {"say": "qa-wee", "mean": ["strong"]},
  "قوی‌تر": {"say": "qa-wee-tar", "mean": ["stronger"]},
  "قیمت": {"say": "qee-mat", "mean": ["price", "expensive"]},
  "قیمت‌ها": {"say": "qee-mat-haa", "mean": ["prices"]},
  "کار": {"say": "kaar", "mean": ["work, job", "thing to do", "کار داشتن: to need"]},
  "کاری": {"say": "kaa-ree", "mean": ["any business", "به او کاری نداشته باشین: leave her alone"]},
  "کاسه": {"say": "kaa-sa", "mean": ["bowl"]},
  "کاکا": {"say": "kaa-kaa", "mean": ["uncle, father's brother", "بچه کاکا: cousin"]},
  "کاکای": {"say": "kaa-kaa-yi", "mean": ["uncle of", "بچه کاکای: the cousin of", "کاکای شو: Uncle Night, the voice on the radio"]},
  "کاکایم": {"say": "kaa-kaa-yum", "mean": ["my uncle, father's brother"]},
  "کالا": {"say": "kaa-laa", "mean": ["clothes"]},
  "کالاها": {"say": "kaa-laa-haa", "mean": ["the clothes"]},
  "کالاهای": {"say": "kaa-laa-haa-yi", "mean": ["the clothes of"]},
  "کالاهایش": {"say": "kaa-laa-haa-yish", "mean": ["his clothes"]},
  "کالای": {"say": "kaa-laa-yi", "mean": ["the clothes of"]},
  "کتاب": {"say": "ki-taab", "mean": ["book"]},
  "کتابچه": {"say": "ki-taab-cha", "mean": ["notebook", "کتابچه حساب: account book"]},
  "کتاب‌های": {"say": "ki-taab-haa-yi", "mean": ["the books of"]},
  "کتاب‌هایی": {"say": "ki-taab-haa-yee", "mean": ["books that"]},
  "کجا": {"say": "ku-jaa", "mean": ["where"]},
  "کچالو": {"say": "ka-chaa-loo", "mean": ["potato, potatoes"]},
  "کد": {"say": "kad", "mean": ["he or she did, made", "پرسان کد: asked"]},
  "کدام": {"say": "ku-daam", "mean": ["which"]},
  "کدم": {"say": "ka-dum", "mean": ["I did"]},
  "کدن": {"say": "ka-dan", "mean": ["they did", "doing"]},
  "کده": {"say": "ka-da", "mean": ["has done", "از ... کده: than"]},
  "کدیم": {"say": "ka-daym", "mean": ["we did"]},
  "کر": {"say": "kar", "mean": ["deaf"]},
  "کریم": {"say": "ka-reem", "mean": ["Karim, a name"]},
  "کس": {"say": "kas", "mean": ["person", "هر کس: anyone, everyone"]},
  "کسی": {"say": "ka-say", "mean": ["someone, anyone"]},
  "کشمش": {"say": "kish-mish", "mean": ["raisins"]},
  "کلان": {"say": "ka-laan", "mean": ["big, large"]},
  "کلاه": {"say": "ku-laa", "mean": ["cap, hat"]},
  "کلید": {"say": "ka-leed", "mean": ["key"]},
  "کلیدش": {"say": "ka-lee-dish", "mean": ["its key"]},
  "کلیدی": {"say": "ka-lee-dee", "mean": ["the key that"]},
  "کم": {"say": "kam", "mean": ["less, little, short of", "کم شدن: to get less"]},
  "کمپل": {"say": "kam-pal", "mean": ["blanket"]},
  "کمر": {"say": "ka-mar", "mean": ["back, the lower back"]},
  "کمره": {"say": "kam-ra", "mean": ["camera"]},
  "کمکم": {"say": "ku-ma-kum", "mean": ["help me", "کمکم نمی‌کنه: doesn't help me"]},
  "کمی": {"say": "ka-may", "mean": ["a little"]},
  "کنم": {"say": "ku-num", "mean": ["that I do"]},
  "کنه": {"say": "ku-na", "mean": ["that he/she does"]},
  "کنین": {"say": "ku-neen", "mean": ["do, the polite form", "حساب کنین: count"]},
  "کوچه": {"say": "koo-cha", "mean": ["lane, street"]},
  "کوشش": {"say": "ko-shish", "mean": ["effort, trying", "کوشش کدن: to try"]},
  "کوه‌ها": {"say": "koh-haa", "mean": ["mountains, the hills"]},
  "که": {"say": "ki", "mean": ["that, which, who"]},
  "کهنه": {"say": "koh-na", "mean": ["old", "Kohna, the old, empty part of the village"]},
  "کی": {"say": "kee", "mean": ["who"]},
  "گاو": {"say": "gaaw", "mean": ["cow"]},
  "گاوها": {"say": "gaaw-haa", "mean": ["cows"]},
  "گاهی": {"say": "gaa-hee", "mean": ["sometimes"]},
  "گپ": {"say": "gap", "mean": ["talk, words", "گپ زدن: to talk"]},
  "گپ‌ها": {"say": "gap-haa", "mean": ["the talk, the things said"]},
  "گپ‌های": {"say": "gap-haa-yi", "mean": ["the talk of, the business of"]},
  "گدام": {"say": "gu-daam", "mean": ["storeroom"]},
  "گذشته": {"say": "gu-zash-ta", "mean": ["last, past", "هفته گذشته: last week"]},
  "گردن": {"say": "gar-dan", "mean": ["neck"]},
  "گرفت": {"say": "gi-rift", "mean": ["took, got", "نام گرفت: said a name"]},
  "گرفتم": {"say": "gi-rif-tum", "mean": ["I took", "تصمیم گرفتم: I decided"]},
  "گرفته": {"say": "gi-rif-ta", "mean": ["taken", "hoarse, of a voice"]},
  "گرم": {"say": "garm", "mean": ["warm"]},
  "گریه": {"say": "gir-ya", "mean": ["crying", "گریه کدن: to cry"]},
  "گفت": {"say": "guft", "mean": ["said, told"]},
  "گفتم": {"say": "guf-tum", "mean": ["I said, I told"]},
  "گفتن": {"say": "guf-tan", "mean": ["they said"]},
  "گفته": {"say": "guf-ta", "mean": ["has said, had told"]},
  "گفتین": {"say": "guf-teen", "mean": ["you said, the polite form"]},
  "گلو": {"say": "ga-loo", "mean": ["throat"]},
  "گم": {"say": "gum", "mean": ["lost, missing", "گم بودن: to be missing"]},
  "گندم": {"say": "gan-dum", "mean": ["wheat"]},
  "گوش": {"say": "gosh", "mean": ["ear", "گوش کدن: to listen"]},
  "گوشت": {"say": "gosht", "mean": ["meat"]},
  "لقمه": {"say": "luq-ma", "mean": ["a bite, a mouthful"]},
  "ما": {"say": "maa", "mean": ["we, us", "our"]},
  "مادر": {"say": "maa-dar", "mean": ["mother"]},
  "مادرم": {"say": "maa-da-rum", "mean": ["my mother"]},
  "ماست": {"say": "maast", "mean": ["yogurt"]},
  "ماشین": {"say": "maa-sheen", "mean": ["machine"]},
  "ماشین‌هایی": {"say": "maa-sheen-haa-yee", "mean": ["machines that"]},
  "ماند": {"say": "maand", "mean": ["put, left, placed", "stayed", "let", "نماند: didn't let"]},
  "ماندم": {"say": "maan-dum", "mean": ["I put, I placed"]},
  "مانده": {"say": "maan-da", "mean": ["tired"]},
  "ماه": {"say": "maah", "mean": ["month", "moon"]},
  "مثل": {"say": "mi-sil", "mean": ["like, as"]},
  "مجاهدین": {"say": "mu-jaa-hi-deen", "mean": ["the mujahideen, fighters against the Soviets"]},
  "مرد": {"say": "mard (died: murd)", "mean": ["man", "died"]},
  "مردا": {"say": "mar-daa", "mean": ["the men"]},
  "مردم": {"say": "mar-dum", "mean": ["people"]},
  "مرغک": {"say": "mur-ghak", "mean": ["a little bird"]},
  "مرغ‌ها": {"say": "murgh-haa", "mean": ["the chickens"]},
  "مزه‌دارتر": {"say": "ma-za-daar-tar", "mean": ["tastier"]},
  "مسجد": {"say": "mas-jid", "mean": ["mosque"]},
  "مشتری‌هایم": {"say": "mush-ta-ree-haa-yum", "mean": ["my customers"]},
  "مشهورتر": {"say": "mash-hoor-tar", "mean": ["more famous"]},
  "معذرت": {"say": "ma-zi-rat", "mean": ["apology", "معذرت خواستن: to say sorry"]},
  "معلم": {"say": "mu-al-lim", "mean": ["teacher", "معلم کریم: Muallim Karim, the teacher"]},
  "معلوم": {"say": "ma-loom", "mean": ["known, clear", "معلوم است: of course, obviously"]},
  "مفت": {"say": "muft", "mean": ["free, for nothing"]},
  "مقبول": {"say": "maq-bool", "mean": ["beautiful", "beautifully"]},
  "مکتب": {"say": "mak-tab", "mean": ["school"]},
  "مکتوب": {"say": "mak-toob", "mean": ["letter"]},
  "مکتوب‌های": {"say": "mak-toob-haa-yi", "mean": ["the letters of"]},
  "مکتوب‌هایش": {"say": "mak-toob-haa-yish", "mean": ["his letters"]},
  "ملک‌های": {"say": "mulk-haa-yi", "mean": ["the countries of", "ملک‌های دگه: other countries"]},
  "منتظر": {"say": "mun-ta-zir", "mean": ["waiting", "منتظر ماندن: to wait"]},
  "موتر": {"say": "mo-tar", "mean": ["car, truck"]},
  "موش‌ها": {"say": "moosh-haa", "mean": ["mice"]},
  "مه": {"say": "ma", "mean": ["I, me"]},
  "مهربان": {"say": "meh-ra-baan", "mean": ["kind"]},
  "میارم": {"say": "may-yaa-rum", "mean": ["I bring"]},
  "میارن": {"say": "may-yaa-ran", "mean": ["they bring"]},
  "میاره": {"say": "may-yaa-ra", "mean": ["brings"]},
  "میاورد": {"say": "may-aa-wurd", "mean": ["used to bring"]},
  "می‌آمد": {"say": "may-aa-mad", "mean": ["used to come"]},
  "می‌آیم": {"say": "may-aa-yum", "mean": ["I come"]},
  "می‌آین": {"say": "may-aa-yan", "mean": ["they come"]},
  "می‌آیه": {"say": "may-aa-ya", "mean": ["comes"]},
  "می‌برم": {"say": "may-ba-rum", "mean": ["I take"]},
  "می‌بود": {"say": "may-bood", "mean": ["were, would be"]},
  "می‌بینن": {"say": "may-bee-nan", "mean": ["they see, they will see"]},
  "می‌پالم": {"say": "may-paa-lum", "mean": ["I look for, I search"]},
  "می‌تانم": {"say": "may-taa-num", "mean": ["I can"]},
  "می‌تانه": {"say": "may-taa-na", "mean": ["can, is able"]},
  "می‌ترسم": {"say": "may-tar-sum", "mean": ["I am afraid"]},
  "می‌ترسن": {"say": "may-tar-san", "mean": ["they are afraid"]},
  "میتم": {"say": "may-tum", "mean": ["I give"]},
  "میتین": {"say": "may-teen", "mean": ["you give, the polite form"]},
  "می‌خایم": {"say": "may-khaa-yum", "mean": ["I want"]},
  "می‌خایه": {"say": "may-khaa-ya", "mean": ["wants"]},
  "می‌خرم": {"say": "may-kha-rum", "mean": ["I buy, I will buy"]},
  "می‌خرن": {"say": "may-kha-ran", "mean": ["they buy, they will buy"]},
  "می‌خره": {"say": "may-kha-ra", "mean": ["buys"]},
  "می‌خواستم": {"say": "may-khaas-tum", "mean": ["I wanted"]},
  "می‌خوانم": {"say": "may-khaa-num", "mean": ["I read, I will read aloud"]},
  "می‌خوانه": {"say": "may-khaa-na", "mean": ["reads"]},
  "می‌خورد": {"say": "may-khord", "mean": ["used to eat"]},
  "می‌خوردم": {"say": "may-khor-dum", "mean": ["I was eating"]},
  "می‌خورم": {"say": "may-kho-rum", "mean": ["I eat"]},
  "می‌خورن": {"say": "may-kho-ran", "mean": ["they eat, they drink"]},
  "می‌خوره": {"say": "may-kho-ra", "mean": ["eats, drinks"]},
  "می‌دوشم": {"say": "may-do-shum", "mean": ["I milk"]},
  "میده": {"say": "may-da", "mean": ["gives"]},
  "میرم": {"say": "may-rum", "mean": ["I go"]},
  "میره": {"say": "may-ra", "mean": ["goes, is going"]},
  "می‌ریخت": {"say": "may-reekht", "mean": ["was pouring"]},
  "می‌ریختم": {"say": "may-reekh-tum", "mean": ["I was pouring"]},
  "می‌ریزم": {"say": "may-ree-zum", "mean": ["I pour"]},
  "می‌زد": {"say": "may-zad", "mean": ["was hitting", "قدم می‌زد: was walking"]},
  "می‌زدن": {"say": "may-za-dan", "mean": ["they used to hit", "گپ می‌زدن: they talked"]},
  "می‌زنم": {"say": "may-za-num", "mean": ["I hit", "گپ می‌زنم: I talk", "چیغ می‌زنم: I shout"]},
  "می‌زنن": {"say": "may-za-nan", "mean": ["they hit", "گپ می‌زنن: they talk"]},
  "می‌زنه": {"say": "may-za-na", "mean": ["hits", "گپ می‌زنه: talks"]},
  "می‌زنیم": {"say": "may-za-neem", "mean": ["we hit", "گپ می‌زنیم: we talk"]},
  "می‌شکنه": {"say": "may-shi-ka-na", "mean": ["breaks, cracks"]},
  "میشم": {"say": "may-shum", "mean": ["I become", "تیر میشم: I cross over"]},
  "می‌شنوم": {"say": "maysh-na-wum", "mean": ["I hear"]},
  "می‌شنون": {"say": "maysh-na-wan", "mean": ["they hear"]},
  "می‌شویم": {"say": "may-sho-yum", "mean": ["I wash"]},
  "میشه": {"say": "may-sha", "mean": ["becomes, gets", "happens"]},
  "می‌شیشتم": {"say": "may-shish-tum", "mean": ["I used to sit"]},
  "می‌شینم": {"say": "may-shee-num", "mean": ["I sit"]},
  "می‌شینن": {"say": "may-shee-nan", "mean": ["they sit"]},
  "می‌شینه": {"say": "may-shee-na", "mean": ["sits"]},
  "می‌شینیم": {"say": "may-shee-neem", "mean": ["we sit"]},
  "می‌فامم": {"say": "may-faa-mum", "mean": ["I know, I understand"]},
  "می‌فامن": {"say": "may-faa-man", "mean": ["they know, they understand"]},
  "می‌فامه": {"say": "may-faa-ma", "mean": ["knows"]},
  "می‌فامید": {"say": "may-faa-meed", "mean": ["would know", "knew"]},
  "می‌فامیدم": {"say": "may-faa-mee-dum", "mean": ["I knew"]},
  "می‌فامین": {"say": "may-faa-meen", "mean": ["you know, you understand, the polite form"]},
  "می‌کد": {"say": "may-kad", "mean": ["he or she used to do", "he or she was doing"]},
  "می‌کدم": {"say": "may-ka-dum", "mean": ["I used to do"]},
  "می‌کدن": {"say": "may-ka-dan", "mean": ["they used to do"]},
  "می‌کنم": {"say": "may-ku-num", "mean": ["I do, I make"]},
  "می‌کنن": {"say": "may-ku-nan", "mean": ["they do, they make"]},
  "می‌کنه": {"say": "may-ku-na", "mean": ["he or she does, makes"]},
  "می‌کنیم": {"say": "may-ku-neem", "mean": ["we do, we make"]},
  "می‌کنین": {"say": "may-ku-neen", "mean": ["you do, the polite form", "پرسان می‌کنین: you ask"]},
  "می‌گردم": {"say": "may-gar-dum", "mean": ["I walk around, I go about"]},
  "می‌گرده": {"say": "may-gar-da", "mean": ["looks around", "پس چیزی گشتن: to look for something"]},
  "می‌گفت": {"say": "may-guft", "mean": ["used to say, was saying"]},
  "میگم": {"say": "may-gum", "mean": ["I say, I tell"]},
  "میگن": {"say": "may-gan", "mean": ["they say"]},
  "میگه": {"say": "may-ga", "mean": ["says, he/she says"]},
  "می‌گیرم": {"say": "may-gee-rum", "mean": ["I take", "تصمیم می‌گیرم: I decide"]},
  "می‌گیره": {"say": "may-gee-ra", "mean": ["takes, gets"]},
  "می‌لرزید": {"say": "may-lar-zeed", "mean": ["was shaking"]},
  "می‌مانم": {"say": "may-maa-num", "mean": ["I stay, I will stay"]},
  "می‌مانن": {"say": "may-maa-nan", "mean": ["they stay"]},
  "می‌نویسم": {"say": "may-na-wee-sum", "mean": ["I write"]},
  "می‌نویسه": {"say": "may-na-wee-sa", "mean": ["writes"]},
  "نام": {"say": "naam", "mean": ["name"]},
  "نان": {"say": "naan", "mean": ["bread", "a meal"]},
  "نباشه": {"say": "na-baa-sha", "mean": ["that he or she isn't"]},
  "نبرده": {"say": "na-bur-da", "mean": ["hasn't taken"]},
  "نبود": {"say": "na-bood", "mean": ["wasn't", "wasn't there"]},
  "نخرید": {"say": "na-kha-reed", "mean": ["didn't buy"]},
  "نخواستم": {"say": "na-khaas-tum", "mean": ["I didn't want, I didn't wish"]},
  "نخواسته": {"say": "na-khaas-ta", "mean": ["hasn't asked for", "معذرت نخواسته: hasn't said sorry"]},
  "نخورد": {"say": "na-khord", "mean": ["didn't eat, didn't drink"]},
  "نداد": {"say": "na-daad", "mean": ["didn't give", "جواب نداد: didn't answer"]},
  "ندادم": {"say": "na-daa-dum", "mean": ["I didn't give", "جواب ندادم: I didn't answer"]},
  "نداده": {"say": "na-daa-da", "mean": ["hasn't given", "یاد نداده: hasn't taught"]},
  "ندارم": {"say": "na-daa-rum", "mean": ["I don't have"]},
  "نداره": {"say": "na-daa-ra", "mean": ["doesn't have", "doesn't need"]},
  "نداشته": {"say": "na-daash-ta", "mean": ["not having", "کاری نداشته باشین: leave alone"]},
  "نرفتم": {"say": "na-raf-tum", "mean": ["I didn't go"]},
  "نرگس": {"say": "nar-gis", "mean": ["Nargis, a name"]},
  "نزد": {"say": "na-zad", "mean": ["didn't hit", "گپ نزد: didn't speak"]},
  "نزدم": {"say": "na-za-dum", "mean": ["I didn't hit", "گپ نزدم: I didn't talk"]},
  "نزدیک": {"say": "naz-deek", "mean": ["near, close to"]},
  "نشان": {"say": "ni-shaan", "mean": ["sign", "نشان دادن: to show"]},
  "نشناخت": {"say": "na-shi-naakht", "mean": ["didn't recognise"]},
  "نشنیدم": {"say": "na-shu-nee-dum", "mean": ["I didn't hear"]},
  "نشنیده": {"say": "na-shu-nee-da", "mean": ["hadn't heard"]},
  "نفامید": {"say": "na-faa-meed", "mean": ["didn't find out"]},
  "نفر": {"say": "na-far", "mean": ["person, when counting people", "پنج نفر: five people"]},
  "نفروختم": {"say": "na-fu-rokh-tum", "mean": ["I didn't sell"]},
  "نفروخته": {"say": "na-fu-rokh-ta", "mean": ["hasn't sold"]},
  "نکد": {"say": "na-kad", "mean": ["didn't do"]},
  "نکدم": {"say": "na-ka-dum", "mean": ["I didn't do", "فکر نکدم: I didn't think"]},
  "نکده": {"say": "na-ka-da", "mean": ["hasn't done, didn't do"]},
  "نگاه": {"say": "ni-gaah", "mean": ["look", "keeping", "نگاه کدن: to keep, to look after"]},
  "نگرفتن": {"say": "na-gi-rif-tan", "mean": ["they didn't take"]},
  "نگفت": {"say": "na-guft", "mean": ["didn't say"]},
  "نگم": {"say": "na-gum", "mean": ["that I don't say"]},
  "نگین": {"say": "na-geen", "mean": ["don't say, don't tell, the polite form"]},
  "نماز": {"say": "na-maaz", "mean": ["prayer, the daily prayers"]},
  "نماند": {"say": "na-maand", "mean": ["didn't let", "didn't put"]},
  "نمره": {"say": "nam-ra", "mean": ["number, mark", "اول نمره: top of the class"]},
  "نمی‌آیه": {"say": "na-may-aa-ya", "mean": ["doesn't come"]},
  "نمی‌بینه": {"say": "na-may-bee-na", "mean": ["doesn't see"]},
  "نمی‌تانم": {"say": "na-may-taa-num", "mean": ["I can't"]},
  "نمی‌تانن": {"say": "na-may-taa-nan", "mean": ["they can't"]},
  "نمی‌تانه": {"say": "na-may-taa-na", "mean": ["can't"]},
  "نمی‌ترسم": {"say": "na-may-tar-sum", "mean": ["I'm not afraid"]},
  "نمی‌خره": {"say": "na-may-kha-ra", "mean": ["doesn't buy"]},
  "نمی‌خوره": {"say": "na-may-kho-ra", "mean": ["doesn't eat, doesn't drink"]},
  "نمی‌داشتیم": {"say": "na-may-daash-teem", "mean": ["we wouldn't have"]},
  "نمیرن": {"say": "na-may-ran", "mean": ["they don't go"]},
  "نمیره": {"say": "na-may-ra", "mean": ["doesn't go"]},
  "نمی‌زنم": {"say": "na-may-za-num", "mean": ["I don't hit", "گپ نمی‌زنم: I don't talk"]},
  "نمی‌زنه": {"say": "na-may-za-na", "mean": ["doesn't hit", "گپ نمی‌زنه: doesn't talk"]},
  "نمیشم": {"say": "na-may-shum", "mean": ["I don't become", "قار نمیشم: I won't be angry"]},
  "نمی‌شناسه": {"say": "na-may-shi-naa-sa", "mean": ["doesn't know, doesn't recognise"]},
  "نمیشه": {"say": "na-may-sha", "mean": ["doesn't become", "doesn't grow"]},
  "نمی‌فامم": {"say": "na-may-faa-mum", "mean": ["I don't know"]},
  "نمی‌فامید": {"say": "na-may-faa-meed", "mean": ["didn't know"]},
  "نمی‌فامین": {"say": "na-may-faa-meen", "mean": ["you don't know, the polite form"]},
  "نمی‌فروشه": {"say": "na-may-fu-ro-sha", "mean": ["doesn't sell, wouldn't sell"]},
  "نمی‌کنم": {"say": "na-may-ku-num", "mean": ["I don't do", "خو نمی‌کنم: I don't sleep"]},
  "نمی‌کنن": {"say": "na-may-ku-nan", "mean": ["they don't do"]},
  "نمی‌کنه": {"say": "na-may-ku-na", "mean": ["he/she doesn't do"]},
  "نمیگه": {"say": "na-may-ga", "mean": ["doesn't say"]},
  "ننوشتم": {"say": "na-na-wish-tum", "mean": ["I didn't write"]},
  "نو": {"say": "naw", "mean": ["new"]},
  "نوشت": {"say": "na-wisht", "mean": ["wrote"]},
  "نوشتم": {"say": "na-wish-tum", "mean": ["I wrote"]},
  "نوشته": {"say": "na-wish-ta", "mean": ["written", "نوشته کدن: to write"]},
  "نه": {"say": "nu", "mean": ["nine", "ساعت نه: nine o'clock"]},
  "نهم": {"say": "nu-hum", "mean": ["ninth"]},
  "نی": {"say": "nay", "mean": ["no"]},
  "نیایه": {"say": "na-yaa-ya", "mean": ["that he doesn't come"]},
  "نیست": {"say": "nayst", "mean": ["is not"]},
  "نیستم": {"say": "nays-tum", "mean": ["I am not"]},
  "و": {"say": "wa", "mean": ["and"]},
  "واز": {"say": "waaz", "mean": ["open"]},
  "واسکت": {"say": "waas-kat", "mean": ["waistcoat"]},
  "واضح": {"say": "waa-zeh", "mean": ["clear"]},
  "واقعاً": {"say": "waa-qi-an", "mean": ["really"]},
  "وحید": {"say": "wa-heed", "mean": ["Wahid, a name"]},
  "وخت": {"say": "wakht", "mean": ["time", "when"]},
  "ورنه": {"say": "war-na", "mean": ["or else, otherwise"]},
  "وقت": {"say": "waqt", "mean": ["early", "time"]},
  "وقتی": {"say": "waq-tay", "mean": ["when"]},
  "هر": {"say": "har", "mean": ["every, each"]},
  "هرات": {"say": "hi-raat", "mean": ["Herat, a city"]},
  "هراتی": {"say": "hi-raa-tee", "mean": ["from Herat", "احمد هراتی: Ahmad from Herat"]},
  "هزار": {"say": "ha-zaar", "mean": ["a thousand"]},
  "هشتاد": {"say": "hash-taad", "mean": ["eighty"]},
  "هفته": {"say": "haf-ta", "mean": ["week"]},
  "هم": {"say": "ham", "mean": ["also, too", "each other"]},
  "همراه": {"say": "ham-raa", "mean": ["with"]},
  "همگی": {"say": "ha-ma-gee", "mean": ["everyone, all"]},
  "همو": {"say": "ha-moo", "mean": ["that same, that very"]},
  "همه": {"say": "ha-ma", "mean": ["all, everyone"]},
  "همه‌شان": {"say": "ha-ma-shaan", "mean": ["all of them"]},
  "همی": {"say": "ha-mee", "mean": ["this same, just this", "همی قدر: just this much"]},
  "همیشه": {"say": "ha-may-sha", "mean": ["always"]},
  "هنوز": {"say": "ha-nooz", "mean": ["still, yet"]},
  "هوا": {"say": "ha-waa", "mean": ["air"]},
  "هوای": {"say": "ha-waa-yi", "mean": ["the air of, the weather of", "هوای سرد: cold air"]},
  "هوشیار": {"say": "hosh-yaar", "mean": ["clever"]},
  "هوشیارتر": {"say": "hosh-yaar-tar", "mean": ["cleverer, smarter"]},
  "هوشیاری": {"say": "hosh-yaa-ree", "mean": ["cleverness"]},
  "هیچ": {"say": "haych", "mean": ["no, none", "any, as in «not any»"]},
  "هیچ‌کس": {"say": "haych-kas", "mean": ["nobody, no one"]},
  "هیچ‌وخت": {"say": "haych-wakht", "mean": ["never"]},
  "هیل": {"say": "hayl", "mean": ["cardamom"]},
  "یا": {"say": "yaa", "mean": ["or"]},
  "یاد": {"say": "yaad", "mean": ["memory", "به یاد داشتن: to remember", "یاد دادن: to teach"]},
  "یافتم": {"say": "yaaf-tum", "mean": ["I found"]},
  "یخ": {"say": "yakh", "mean": ["ice"]},
  "یک": {"say": "yak", "mean": ["a, one"]},
  "یکجایی": {"say": "yak-jaa-yee", "mean": ["together"]},
  "یکشنبه": {"say": "yak-sham-ba", "mean": ["Sunday"]},
  "یکی": {"say": "ya-kee", "mean": ["one of them"]},
  "یگانه": {"say": "ya-gaa-na", "mean": ["only, single"]}
};
