/* The game's dictionary: every word spoken in the recordings, written as
   it is on the paper, with how to say it and its English meaning. Clicking
   a word on the paper shows both.

   "mean" is a list of lines, one meaning on each line and no brackets. A
   Dari phrase with the word gets a line of its own: the phrase, a colon,
   then its English, as in "به یاد داشتن: to remember".

   "say" spells the colloquial Kabul Dari sound in English letters, one
   hyphen between syllables: aa as in father, a as in cat, ay as in say,
   ee as in see, i as in sit, o as in go, oo as in food, u as in put,
   aw as in cow. kh is the rough h in Scottish loch, gh is a French r,
   q is a k made deep in the throat.

   Hand-edited: change a word here, then run python build/make_dictionary.py
   to refresh story_elements/dictionary.md and to list any spoken word that
   has no entry yet. */
var JINN_GLOSSARY = {
  "اتاق": {"say": "u-taaq", "mean": ["room"]},
  "اتاقش": {"say": "u-taa-qish", "mean": ["her room"]},
  "اتاقم": {"say": "u-taa-qum", "mean": ["my room"]},
  "احترام": {"say": "eh-ti-raam", "mean": ["respect", "با احترام: politely"]},
  "احتیاط": {"say": "eh-ti-yaat", "mean": ["care, caution", "احتیاط کدن: to be careful"]},
  "احوال": {"say": "ah-waal", "mean": ["news of someone"]},
  "اذان": {"say": "a-zaan", "mean": ["the call to prayer"]},
  "از": {"say": "az", "mean": ["from", "of", "than"]},
  "ازش": {"say": "a-zish", "mean": ["from him/her", "of it"]},
  "اسپ‌های": {"say": "asp-haay", "mean": ["the horses of"]},
  "است": {"say": "ast", "mean": ["is"]},
  "استادم": {"say": "us-taa-dum", "mean": ["my teacher"]},
  "استراحت": {"say": "is-ti-raa-hat", "mean": ["rest", "استراحت کدن: to rest"]},
  "استم": {"say": "as-tum", "mean": ["I am"]},
  "استن": {"say": "as-tan", "mean": ["they are"]},
  "افتادن": {"say": "uf-taa-dan", "mean": ["they fell"]},
  "اکثرشان": {"say": "ak-sar-shaan", "mean": ["most of them"]},
  "اگر": {"say": "a-gar", "mean": ["if"]},
  "الیکین": {"say": "a-lee-kayn", "mean": ["oil lamp, hurricane lamp"]},
  "امروز": {"say": "im-roz", "mean": ["today"]},
  "امسال": {"say": "im-saal", "mean": ["this year"]},
  "امشو": {"say": "im-shaw", "mean": ["tonight"]},
  "امصبح": {"say": "im-subh", "mean": ["this morning"]},
  "امید": {"say": "u-meed", "mean": ["hope"]},
  "انتخاب": {"say": "in-ti-khaab", "mean": ["choice", "انتخاب کدن: to choose"]},
  "انتظار": {"say": "in-ti-zaar", "mean": ["waiting"]},
  "انجیل": {"say": "in-jeel", "mean": ["Injil, a district of Herat"]},
  "انداخت": {"say": "an-daakht", "mean": ["threw"]},
  "انگور": {"say": "an-goor", "mean": ["grapes"]},
  "انگورها": {"say": "an-goor-haa", "mean": ["grapes"]},
  "انگورهای": {"say": "an-goor-haa-yi", "mean": ["grapes of"]},
  "او": {"say": "oo", "mean": ["he, she", "that"]},
  "اول": {"say": "aw-wal", "mean": ["first"]},
  "اولین": {"say": "aw-wa-leen", "mean": ["the first"]},
  "اونا": {"say": "oo-naa", "mean": ["they, them", "those"]},
  "اونایی": {"say": "oo-naa-yay", "mean": ["those who, the ones"]},
  "اونجه": {"say": "oon-ja", "mean": ["there"]},
  "ای": {"say": "ee", "mean": ["this"]},
  "ایران": {"say": "ee-raan", "mean": ["Iran"]},
  "ایستاد": {"say": "ees-taad", "mean": ["standing", "ایستاد شدن: to stand"]},
  "ایستگاه": {"say": "ees-ti-gaah", "mean": ["station", "ایستگاه بس: bus station"]},
  "ایطو": {"say": "ee-to", "mean": ["like this, this way"]},
  "ایقه": {"say": "ee-qa", "mean": ["this much, so much"]},
  "این": {"say": "een", "mean": ["this"]},
  "اینجه": {"say": "een-ja", "mean": ["here"]},
  "آب‌بازی": {"say": "aab-baa-zee", "mean": ["swimming"]},
  "آبی": {"say": "aa-bee", "mean": ["blue"]},
  "آتش": {"say": "aa-tash", "mean": ["fire"]},
  "آخر": {"say": "aa-khir", "mean": ["last", "the end"]},
  "آخرین": {"say": "aa-khi-reen", "mean": ["the last"]},
  "آدرس": {"say": "aad-ras", "mean": ["address"]},
  "آدم": {"say": "aa-dam", "mean": ["person, human"]},
  "آرام": {"say": "aa-raam", "mean": ["quiet, quietly", "calm"]},
  "آرامش": {"say": "aa-raa-mish", "mean": ["peace, rest"]},
  "آسان": {"say": "aa-saan", "mean": ["easy"]},
  "آفتاب": {"say": "aaf-taab", "mean": ["sun"]},
  "آمد": {"say": "aa-mad", "mean": ["came"]},
  "آمدن": {"say": "aa-ma-dan", "mean": ["they came", "coming"]},
  "آمده": {"say": "aa-ma-da", "mean": ["come", "پایان آمده نتانست: couldn't come down"]},
  "آمدیم": {"say": "aa-ma-daym", "mean": ["we came"]},
  "آو": {"say": "aaw", "mean": ["water"]},
  "آورد": {"say": "aa-ward", "mean": ["brought"]},
  "آوردم": {"say": "aa-war-dum", "mean": ["I brought", "به یاد آوردم: I remembered"]},
  "با": {"say": "baa", "mean": ["with"]},
  "بار": {"say": "baar", "mean": ["time", "اولین بار: the first time"]},
  "باران": {"say": "baa-raan", "mean": ["rain"]},
  "بارید": {"say": "baa-reed", "mean": ["fell, of rain or snow"]},
  "باز": {"say": "baaz", "mean": ["again"]},
  "بازار": {"say": "baa-zaar", "mean": ["bazaar, market"]},
  "بازی": {"say": "baa-zee", "mean": ["play, game", "بازی کدن: to play"]},
  "باشم": {"say": "baa-shum", "mean": ["that I am"]},
  "باشه": {"say": "baa-sha", "mean": ["that it is, may be"]},
  "باغ": {"say": "baagh", "mean": ["garden, orchard", "باغ تاک: vineyard"]},
  "باغ‌های": {"say": "baagh-haay", "mean": ["the gardens of", "باغ‌های تاک: vineyards"]},
  "بالا": {"say": "baa-laa", "mean": ["up"]},
  "بالاخره": {"say": "bil-aa-khi-ra", "mean": ["finally, at last"]},
  "بالای": {"say": "baa-laa-yi", "mean": ["above, over"]},
  "بالشت": {"say": "baa-lisht", "mean": ["pillow"]},
  "بام": {"say": "baam", "mean": ["roof"]},
  "بامش": {"say": "baa-mish", "mean": ["its roof"]},
  "بام‌های": {"say": "baam-haay", "mean": ["the roofs of"]},
  "باور": {"say": "baa-war", "mean": ["belief", "باور کدن: to believe"]},
  "باید": {"say": "baa-yad", "mean": ["must, should"]},
  "ببینم": {"say": "bi-bee-num", "mean": ["that I see"]},
  "ببینین": {"say": "bi-bee-nayn", "mean": ["see, the polite form for you"]},
  "بتم": {"say": "bi-tum", "mean": ["that I give"]},
  "بتن": {"say": "bi-tan", "mean": ["that they give"]},
  "بته": {"say": "bi-ta", "mean": ["that he gives", "یاد بته: that he teaches"]},
  "بچه": {"say": "ba-cha", "mean": ["son, boy", "child"]},
  "بچه‌ام": {"say": "ba-cha-um", "mean": ["my son"]},
  "بچه‌ها": {"say": "ba-cha-haa", "mean": ["boys, children"]},
  "بچه‌های": {"say": "ba-cha-haa-yi", "mean": ["the sons, the children of"]},
  "بچه‌هایش": {"say": "ba-cha-haa-yish", "mean": ["his/her sons, children"]},
  "بچه‌هایم": {"say": "ba-cha-haa-yum", "mean": ["my sons, my children"]},
  "بخاطر": {"say": "ba-khaa-tir", "mean": ["because of"]},
  "بخاطری": {"say": "ba-khaa-ti-ray", "mean": ["because", "بخاطری که: because"]},
  "بخوانم": {"say": "bi-khaa-num", "mean": ["that I read"]},
  "بخوانه": {"say": "bi-khaa-na", "mean": ["that he reads, he says a prayer"]},
  "بد": {"say": "bad", "mean": ["bad"]},
  "بددعا": {"say": "bad-du-aa", "mean": ["curse", "بددعا کدن: to curse"]},
  "بدل": {"say": "ba-dal", "mean": ["changed", "بدل کدن: to change"]},
  "بر": {"say": "bar", "mean": ["memory", "از بر: by heart"]},
  "برادر": {"say": "ba-raa-dar", "mean": ["brother"]},
  "برادرا": {"say": "ba-raa-da-raa", "mean": ["the brothers"]},
  "برادرانم": {"say": "ba-raa-da-raa-num", "mean": ["my brothers"]},
  "برادرم": {"say": "ba-raa-da-rum", "mean": ["my brother"]},
  "برایش": {"say": "ba-raa-yish", "mean": ["for him/her", "to him/her"]},
  "برای‌شان": {"say": "ba-raa-yi-shaan", "mean": ["for them", "to them"]},
  "برایم": {"say": "ba-raa-yum", "mean": ["to me, for me"]},
  "برد": {"say": "burd", "mean": ["took, carried"]},
  "برداشته": {"say": "bar-daash-ta", "mean": ["has taken away, has picked up"]},
  "بردم": {"say": "bur-dum", "mean": ["I took, I carried"]},
  "بردن": {"say": "bur-dan", "mean": ["they took"]},
  "برف": {"say": "barf", "mean": ["snow"]},
  "برم": {"say": "bu-rum", "mean": ["that I go"]},
  "برن": {"say": "bu-ran", "mean": ["that they go"]},
  "بره": {"say": "bu-ra", "mean": ["that he/she goes"]},
  "بری": {"say": "ba-ray", "mean": ["for"]},
  "بریم": {"say": "bu-raym", "mean": ["that we go"]},
  "بزنه": {"say": "bi-za-na", "mean": ["that he hits", "گپ بزنه: that he talks"]},
  "بزنیم": {"say": "bi-za-naym", "mean": ["that we hit", "گپ بزنیم: that we talk"]},
  "بزها": {"say": "buz-haa", "mean": ["goats"]},
  "بزهایش": {"say": "buz-haa-yish", "mean": ["her goats"]},
  "بس": {"say": "bas", "mean": ["enough", "stopped", "بس کدن: to stop"]},
  "بسته": {"say": "bas-ta", "mean": ["closed, shut"]},
  "بسوزانم": {"say": "bi-so-zaa-num", "mean": ["that I burn"]},
  "بسیار": {"say": "bis-yaar", "mean": ["very, much", "a lot"]},
  "بسیارشان": {"say": "bis-yaar-shaan", "mean": ["many of them"]},
  "بشانه": {"say": "bi-shaa-na", "mean": ["that he plants"]},
  "بشنوم": {"say": "bish-na-wum", "mean": ["that I hear"]},
  "بشنون": {"say": "bish-na-wan", "mean": ["that they hear"]},
  "بشیر": {"say": "ba-sheer", "mean": ["Bashir, a name"]},
  "بعد": {"say": "baad", "mean": ["after", "then, later"]},
  "بعداً": {"say": "baa-dan", "mean": ["later"]},
  "بعدش": {"say": "baa-dish", "mean": ["after that, then"]},
  "بعضی": {"say": "baa-zay", "mean": ["some"]},
  "بعضی‌شان": {"say": "baa-zee-shaan", "mean": ["some of them"]},
  "بغل": {"say": "ba-ghal", "mean": ["side, beside"]},
  "بقه‌ها": {"say": "ba-qa-haa", "mean": ["frogs"]},
  "بکس": {"say": "baks", "mean": ["bag"]},
  "بکسم": {"say": "bak-sum", "mean": ["my bag"]},
  "بکشه": {"say": "bu-ku-sha", "mean": ["that it kills"]},
  "بکنم": {"say": "bu-ku-num", "mean": ["that I dig"]},
  "بگیرن": {"say": "bi-gee-ran", "mean": ["that they take", "تصمیم بگیرن: that they decide"]},
  "بگیره": {"say": "bi-gee-ra", "mean": ["that he takes"]},
  "بلند": {"say": "ba-land", "mean": ["loud, loudly", "high"]},
  "بلندتر": {"say": "ba-land-tar", "mean": ["louder"]},
  "بمانن": {"say": "bi-maa-nan", "mean": ["that they stay"]},
  "بمانه": {"say": "bi-maa-na", "mean": ["that he/she puts", "that he/she stays"]},
  "بمب": {"say": "bamb", "mean": ["bomb"]},
  "بمیرم": {"say": "bi-mee-rum", "mean": ["that I die"]},
  "بوت": {"say": "boot", "mean": ["shoe, boot"]},
  "بوت‌های": {"say": "boot-haay", "mean": ["the shoes, the boots of"]},
  "بوتی": {"say": "boo-tay", "mean": ["any shoe", "هیچ بوتی: no shoe"]},
  "بود": {"say": "bood", "mean": ["was"]},
  "بودم": {"say": "boo-dum", "mean": ["I was"]},
  "بودن": {"say": "boo-dan", "mean": ["they were"]},
  "بوده": {"say": "boo-da", "mean": ["has been, was"]},
  "بودیم": {"say": "boo-daym", "mean": ["we were"]},
  "بوره": {"say": "boo-ra", "mean": ["sugar"]},
  "بوی": {"say": "boo-yi", "mean": ["the smell of"]},
  "به": {"say": "ba", "mean": ["to"]},
  "بهار": {"say": "ba-haar", "mean": ["spring, the season"]},
  "بهتر": {"say": "bih-tar", "mean": ["better"]},
  "بهترین": {"say": "bih-ta-reen", "mean": ["the best"]},
  "بی": {"say": "bay", "mean": ["without"]},
  "بیاریم": {"say": "bi-yaa-raym", "mean": ["that we bring"]},
  "بیایه": {"say": "bi-yaa-ya", "mean": ["that it comes"]},
  "بی‌جای": {"say": "bay-jaay", "mean": ["out of place, in the wrong order"]},
  "بی‌خطر": {"say": "bay-kha-tar", "mean": ["safe"]},
  "بیرون": {"say": "bay-roon", "mean": ["outside, out"]},
  "بین‌شان": {"say": "bayn-shaan", "mean": ["between them"]},
  "بیوه": {"say": "bay-wa", "mean": ["widow"]},
  "پاک": {"say": "paak", "mean": ["clean"]},
  "پاهایش": {"say": "paa-haa-yish", "mean": ["her feet"]},
  "پای": {"say": "paa-yi", "mean": ["foot of"]},
  "پایان": {"say": "paa-yaan", "mean": ["down"]},
  "پایش": {"say": "paa-yish", "mean": ["his leg, his foot"]},
  "پختن": {"say": "pukh-tan", "mean": ["baking"]},
  "پخته": {"say": "pukh-ta", "mean": ["cooked, baked", "پخته کدن: to bake"]},
  "پدر": {"say": "pa-dar", "mean": ["father"]},
  "پدرش": {"say": "pa-da-rish", "mean": ["his/her father"]},
  "پدرشان": {"say": "pa-dar-shaan", "mean": ["their father"]},
  "پدرکلان": {"say": "pa-dar-ka-laan", "mean": ["grandfather"]},
  "پدرم": {"say": "pa-da-rum", "mean": ["my father"]},
  "پر": {"say": "pur", "mean": ["full", "filled"]},
  "پرسان": {"say": "pur-saan", "mean": ["asking", "پرسان کدن: to ask"]},
  "پس": {"say": "pas", "mean": ["back again", "so, then", "behind"]},
  "پسش": {"say": "pa-sish", "mean": ["after him, behind him"]},
  "پسم": {"say": "pa-sum", "mean": ["after me, behind me"]},
  "پسِ": {"say": "pa-si", "mean": ["behind, after"]},
  "پشت": {"say": "pusht", "mean": ["behind", "back"]},
  "پشتشان": {"say": "push-ti-shaan", "mean": ["behind them"]},
  "پشیمان": {"say": "pa-shay-maan", "mean": ["sorry, regretful"]},
  "پل": {"say": "pul", "mean": ["bridge"]},
  "پلو": {"say": "pa-loo", "mean": ["beside, next to"]},
  "پلویم": {"say": "pa-loo-yum", "mean": ["beside me"]},
  "پنجشنبه": {"say": "panj-sham-ba", "mean": ["Thursday"]},
  "پنجشنبه‌ها": {"say": "panj-sham-ba-haa", "mean": ["on Thursdays"]},
  "پوست": {"say": "post", "mean": ["skin, peel", "پوست پیاز: onion skin"]},
  "پوسیده": {"say": "po-see-da", "mean": ["rotten"]},
  "پوشیده": {"say": "po-shee-da", "mean": ["had put on, wearing"]},
  "پیاز": {"say": "pee-yaaz", "mean": ["onion"]},
  "پیر": {"say": "peer", "mean": ["old, of people"]},
  "پیسه": {"say": "pay-sa", "mean": ["money"]},
  "پیش": {"say": "paysh", "mean": ["before", "near, at someone's place"]},
  "پیشش": {"say": "pay-shish", "mean": ["to her, at her side"]},
  "پیشم": {"say": "pay-shum", "mean": ["to me, to my place"]},
  "تا": {"say": "taa", "mean": ["until", "so that"]},
  "تاریک": {"say": "taa-reek", "mean": ["dark"]},
  "تاریک‌تر": {"say": "taa-reek-tar", "mean": ["darker"]},
  "تاریکی": {"say": "taa-ree-kee", "mean": ["darkness, dark"]},
  "تازه": {"say": "taa-za", "mean": ["fresh", "just now"]},
  "تاک": {"say": "taak", "mean": ["grapevine"]},
  "تاک‌های": {"say": "taak-haay", "mean": ["the vines of"]},
  "تب": {"say": "tab", "mean": ["fever"]},
  "تر": {"say": "tar", "mean": ["wet"]},
  "ترس": {"say": "tars", "mean": ["fear"]},
  "تصمیم": {"say": "tas-meem", "mean": ["decision"]},
  "تقریباً": {"say": "taq-ree-ban", "mean": ["almost"]},
  "تک": {"say": "tak", "mean": ["knock", "تک تک: knocking"]},
  "تک‌شه": {"say": "tak-sha", "mean": ["its ticking", "تک تک‌شه: its ticking"]},
  "تکه": {"say": "ti-ka", "mean": ["cloth, piece of cloth"]},
  "تمام": {"say": "ta-maam", "mean": ["all, the whole"]},
  "تمام‌شان": {"say": "ta-maam-shaan", "mean": ["all of them"]},
  "تنور": {"say": "ta-noor", "mean": ["tandur, a clay bread oven"]},
  "تنها": {"say": "tan-haa", "mean": ["alone"]},
  "توت": {"say": "toot", "mean": ["mulberry, mulberries"]},
  "توت‌های": {"say": "toot-haay", "mean": ["the mulberries of"]},
  "تولد": {"say": "ta-wal-lud", "mean": ["birth"]},
  "تیار": {"say": "tay-yaar", "mean": ["ready"]},
  "تیر": {"say": "tayr", "mean": ["past", "تیر شدن: to pass by, to go past"]},
  "تیز": {"say": "tayz", "mean": ["quickly, fast"]},
  "تیل": {"say": "tayl", "mean": ["oil, lamp oil"]},
  "ثبوت": {"say": "su-boot", "mean": ["proof"]},
  "جا": {"say": "jaa", "mean": ["place"]},
  "جانش": {"say": "jaa-nish", "mean": ["its body"]},
  "جاها": {"say": "jaa-haa", "mean": ["places"]},
  "جاهای": {"say": "jaa-haay", "mean": ["places"]},
  "جاهایی": {"say": "jaa-haa-yay", "mean": ["places where"]},
  "جای": {"say": "jaa-yi", "mean": ["place", "جای خواب: bed"]},
  "جایی": {"say": "jaa-yay", "mean": ["a place where"]},
  "جدا": {"say": "ju-daa", "mean": ["separate, different"]},
  "جز": {"say": "juz", "mean": ["except"]},
  "جمعه": {"say": "ju-ma", "mean": ["Friday"]},
  "جن": {"say": "jin", "mean": ["jinn, a spirit"]},
  "جنازه": {"say": "ja-naa-za", "mean": ["funeral", "نماز جنازه: funeral prayer"]},
  "جنجال": {"say": "jan-jaal", "mean": ["trouble, quarrel"]},
  "جنگ": {"say": "jang", "mean": ["war"]},
  "جنگید": {"say": "jan-geed", "mean": ["fought"]},
  "جن‌ها": {"say": "jin-haa", "mean": ["jinns, spirits"]},
  "جواب": {"say": "ja-waab", "mean": ["answer"]},
  "جوان": {"say": "ja-waan", "mean": ["young"]},
  "جوان‌ها": {"say": "ja-waan-haa", "mean": ["young people"]},
  "جور": {"say": "jor", "mean": ["built, made", "fine, sound", "جور کدن: to build"]},
  "جوی": {"say": "jooy", "mean": ["canal, irrigation channel"]},
  "جویچه": {"say": "jooy-cha", "mean": ["small channel"]},
  "جیب": {"say": "jayb", "mean": ["pocket"]},
  "چارطراف": {"say": "chaar-ta-raaf", "mean": ["all around"]},
  "چاشت": {"say": "chaasht", "mean": ["noon, midday"]},
  "چاقوی": {"say": "chaa-qoo-yi", "mean": ["the knife of"]},
  "چاقویش": {"say": "chaa-qoo-yish", "mean": ["his knife"]},
  "چاه": {"say": "chaah", "mean": ["a well, for water"]},
  "چپ": {"say": "chup", "mean": ["quiet, silent"]},
  "چپه": {"say": "chap-pa", "mean": ["overturned, fallen", "چپه شدن: to fall in, to collapse"]},
  "چرا": {"say": "chi-raa", "mean": ["why"]},
  "چشم‌ها": {"say": "chashm-haa", "mean": ["eyes"]},
  "چطور": {"say": "chi-tawr", "mean": ["how"]},
  "چند": {"say": "chand", "mean": ["a few, several", "how many"]},
  "چوب": {"say": "choob", "mean": ["wood", "beam"]},
  "چوب‌ها": {"say": "choob-haa", "mean": ["the beams, the pieces of wood"]},
  "چوب‌های": {"say": "choob-haay", "mean": ["the pieces of wood, the beams of"]},
  "چوپان": {"say": "cho-paan", "mean": ["shepherd"]},
  "چی": {"say": "chee", "mean": ["what"]},
  "چیز": {"say": "cheez", "mean": ["thing"]},
  "چیزها": {"say": "cheez-haa", "mean": ["things"]},
  "چیزهای": {"say": "cheez-haay", "mean": ["things"]},
  "چیزی": {"say": "chee-zay", "mean": ["something, anything"]},
  "حاصلات": {"say": "haa-si-laat", "mean": ["harvest"]},
  "حال": {"say": "haal", "mean": ["state", "به هر حال: anyway"]},
  "حالا": {"say": "haa-laa", "mean": ["now"]},
  "حتی": {"say": "hat-taa", "mean": ["even"]},
  "حصه": {"say": "his-sa", "mean": ["part"]},
  "حفاظت": {"say": "hi-faa-zat", "mean": ["protection"]},
  "حکومت": {"say": "hu-koo-mat", "mean": ["government"]},
  "حمید": {"say": "ha-meed", "mean": ["Hamid, a name"]},
  "حویلی": {"say": "haw-lee", "mean": ["courtyard"]},
  "حیوانات": {"say": "hay-waa-naat", "mean": ["animals"]},
  "خاک": {"say": "khaak", "mean": ["earth, soil"]},
  "خالی": {"say": "khaa-lee", "mean": ["empty"]},
  "خام": {"say": "khaam", "mean": ["raw", "خشت خام: unbaked mud brick"]},
  "خانم": {"say": "khaa-num", "mean": ["wife of"]},
  "خانمم": {"say": "khaa-nu-mum", "mean": ["my wife"]},
  "خانه": {"say": "khaa-na", "mean": ["house, home"]},
  "خانه‌ام": {"say": "khaa-na-um", "mean": ["my house"]},
  "خانه‌ای": {"say": "khaa-na-ee", "mean": ["the house that"]},
  "خان‌های": {"say": "khaan-haay", "mean": ["the khans, the landlords of"]},
  "خانه‌شان": {"say": "khaa-na-shaan", "mean": ["their house"]},
  "خانه‌ها": {"say": "khaa-na-haa", "mean": ["houses"]},
  "خانه‌های": {"say": "khaa-na-haay", "mean": ["the houses of"]},
  "خبر": {"say": "kha-bar", "mean": ["news", "خبر شدن: to hear about, to learn"]},
  "خر": {"say": "khar", "mean": ["donkey"]},
  "خراب": {"say": "kha-raab", "mean": ["bad, broken"]},
  "خراب‌ترین": {"say": "kha-raab-ta-reen", "mean": ["the worst"]},
  "خرد": {"say": "khurd", "mean": ["small, little", "young"]},
  "خردی": {"say": "khur-day", "mean": ["a small one"]},
  "خریطه": {"say": "kha-ree-ta", "mean": ["bag, sack"]},
  "خزان": {"say": "kha-zaan", "mean": ["autumn"]},
  "خسر": {"say": "khu-sur", "mean": ["father-in-law"]},
  "خشت": {"say": "khisht", "mean": ["mud brick"]},
  "خشت‌ها": {"say": "khisht-haa", "mean": ["the bricks"]},
  "خشت‌های": {"say": "khisht-haay", "mean": ["the mud bricks of"]},
  "خشک": {"say": "khushk", "mean": ["dry, dried"]},
  "خشکشه": {"say": "khush-ki-sha", "mean": ["its dry wood"]},
  "خشن": {"say": "kha-shin", "mean": ["rough"]},
  "خشویم": {"say": "khu-shoo-yum", "mean": ["my mother-in-law"]},
  "خط": {"say": "khat", "mean": ["letter"]},
  "خطرناک": {"say": "kha-tar-naak", "mean": ["dangerous"]},
  "خط‌ها": {"say": "khat-haa", "mean": ["letters"]},
  "خط‌های": {"say": "khat-haay", "mean": ["the letters of"]},
  "خطی": {"say": "kha-tay", "mean": ["a letter, any letter"]},
  "خفتن": {"say": "khuf-tan", "mean": ["night prayer", "نماز خفتن: the night prayer"]},
  "خلاص": {"say": "kha-laas", "mean": ["finished", "خلاص کدن: to finish"]},
  "خنده": {"say": "khan-da", "mean": ["laughter", "خنده کدن: to laugh"]},
  "خنک": {"say": "khu-nuk", "mean": ["cold", "خنک خوردن: to be cold"]},
  "خو": {"say": "kho (sleep: khaw)", "mean": ["but", "sleep", "خو کدن: to sleep", "خو دیدن: to dream"]},
  "خواب": {"say": "khaab", "mean": ["sleep", "جای خواب: bed"]},
  "خوابم": {"say": "khaa-bum", "mean": ["my sleep", "جای خوابم: my bed"]},
  "خواست": {"say": "khaast", "mean": ["wanted", "asked for"]},
  "خواستگاریم": {"say": "khaas-ta-gaa-ree-um", "mean": ["asking for my hand in marriage"]},
  "خواستم": {"say": "khaas-tum", "mean": ["I asked for, I wanted"]},
  "خواندم": {"say": "khaan-dum", "mean": ["I read aloud", "I prayed"]},
  "خواهر": {"say": "khaa-har", "mean": ["sister"]},
  "خواهرم": {"say": "khaa-ha-rum", "mean": ["my sister"]},
  "خوب": {"say": "khoob", "mean": ["good", "well"]},
  "خوبی": {"say": "khoo-bay", "mean": ["good ones"]},
  "خود": {"say": "khud", "mean": ["own", "self"]},
  "خودم": {"say": "khu-dum", "mean": ["myself"]},
  "خوردن": {"say": "khor-dan", "mean": ["eating"]},
  "خوش": {"say": "khush", "mean": ["happy, pleased", "خوش داشتن: to like"]},
  "خون": {"say": "khoon", "mean": ["blood"]},
  "داخل": {"say": "daa-khil", "mean": ["inside"]},
  "داخلش": {"say": "daa-khi-lish", "mean": ["inside it"]},
  "داد": {"say": "daad", "mean": ["gave"]},
  "دادم": {"say": "daa-dum", "mean": ["I gave"]},
  "دادن": {"say": "daa-dan", "mean": ["they gave"]},
  "داده": {"say": "daa-da", "mean": ["has given, gave"]},
  "دارم": {"say": "daa-rum", "mean": ["I have"]},
  "دارن": {"say": "daa-ran", "mean": ["they have"]},
  "داره": {"say": "daa-ra", "mean": ["has"]},
  "دارین": {"say": "daa-rayn", "mean": ["you have, the polite form", "کار دارین: you need"]},
  "داشت": {"say": "daasht", "mean": ["had"]},
  "داشتم": {"say": "daash-tum", "mean": ["I had"]},
  "داشتن": {"say": "daash-tan", "mean": ["they had"]},
  "داشته": {"say": "daash-ta", "mean": ["had", "داشته باشه: might have"]},
  "دختر": {"say": "dukh-tar", "mean": ["girl, daughter"]},
  "دخترا": {"say": "dukh-ta-raa", "mean": ["girls"]},
  "دخترک": {"say": "dukh-ta-rak", "mean": ["little girl"]},
  "درباره": {"say": "dar-baa-ra", "mean": ["about"]},
  "درباره‌اش": {"say": "dar-baa-ra-ash", "mean": ["about it, about him"]},
  "درخت": {"say": "da-rakht", "mean": ["tree"]},
  "درخت‌های": {"say": "da-rakht-haay", "mean": ["the trees of"]},
  "درست": {"say": "du-rust", "mean": ["right, correct"]},
  "دروازه": {"say": "dar-waa-za", "mean": ["gate, door"]},
  "دروازه‌اش": {"say": "dar-waa-za-ash", "mean": ["her door"]},
  "دروازه‌ام": {"say": "dar-waa-za-um", "mean": ["my gate"]},
  "دروازه‌شه": {"say": "dar-waa-za-sha", "mean": ["its door, its doorway"]},
  "دروازه‌ها": {"say": "dar-waa-za-haa", "mean": ["doors, gates"]},
  "دزدها": {"say": "duzd-haa", "mean": ["thieves"]},
  "دست": {"say": "dast", "mean": ["hand"]},
  "دستمالش": {"say": "dast-maa-lish", "mean": ["her cloth"]},
  "دعا": {"say": "du-aa", "mean": ["prayer, asking God"]},
  "دعای": {"say": "du-aa-yi", "mean": ["the prayer of, the prayer for"]},
  "دفعه": {"say": "daf-a", "mean": ["time, occasion", "سه دفعه: three times"]},
  "دفعه‌ها": {"say": "daf-a-haa", "mean": ["times"]},
  "دفن": {"say": "dafn", "mean": ["buried", "دفن شدن: to be buried"]},
  "دگه": {"say": "di-ga", "mean": ["other", "more", "any more", "دگه نه: no longer"]},
  "دگه‌شه": {"say": "di-ga-sha", "mean": ["the other one"]},
  "دلش": {"say": "di-lish", "mean": ["her heart", "دلش است: she wants"]},
  "دلیلی": {"say": "da-lee-lay", "mean": ["a reason, any reason"]},
  "دم": {"say": "dam", "mean": ["moment", "یک دم: suddenly"]},
  "دو": {"say": "du", "mean": ["two"]},
  "دور": {"say": "door", "mean": ["far, away"]},
  "دوستای": {"say": "dos-taa-yi", "mean": ["friends of"]},
  "دوستایش": {"say": "dos-taa-yish", "mean": ["his friends"]},
  "دوستش": {"say": "dos-tish", "mean": ["his friend"]},
  "دوستم": {"say": "dos-tum", "mean": ["my friend"]},
  "دوی‌شان": {"say": "du-yi-shaan", "mean": ["the two of them", "هر دوی‌شان: both of them"]},
  "دویشان": {"say": "du-yi-shaan", "mean": ["the two of them", "هر دویشان: both of them"]},
  "ده": {"say": "da", "mean": ["in, at, into"]},
  "دهانش": {"say": "da-haa-nish", "mean": ["her mouth, his mouth"]},
  "دهقانی": {"say": "deh-qaa-nee", "mean": ["farming"]},
  "دید": {"say": "deed", "mean": ["saw"]},
  "دیدم": {"say": "dee-dum", "mean": ["I saw"]},
  "دیدن": {"say": "dee-dan", "mean": ["they saw", "seeing"]},
  "دیده": {"say": "dee-da", "mean": ["has seen, had seen"]},
  "دیروز": {"say": "day-roz", "mean": ["yesterday"]},
  "دیشام": {"say": "day-shaam", "mean": ["yesterday evening"]},
  "دیشو": {"say": "day-shaw", "mean": ["last night"]},
  "دیگ": {"say": "dayg", "mean": ["pot"]},
  "دیگ‌ها": {"say": "dayg-haa", "mean": ["pots"]},
  "دین": {"say": "deen", "mean": ["religion"]},
  "دیوار": {"say": "day-waar", "mean": ["wall"]},
  "دیوارها": {"say": "day-waar-haa", "mean": ["walls"]},
  "دیواری": {"say": "day-waa-ray", "mean": ["the wall that"]},
  "دیوانه": {"say": "day-waa-na", "mean": ["mad, out of her mind"]},
  "رازهای": {"say": "raaz-haay", "mean": ["the secrets of"]},
  "راست": {"say": "raast", "mean": ["true"]},
  "راه": {"say": "raah", "mean": ["path, road, way"]},
  "راه‌شان": {"say": "raah-shaan", "mean": ["their journey, their way"]},
  "راه‌ها": {"say": "raah-haa", "mean": ["the roads"]},
  "راه‌های": {"say": "raah-haay", "mean": ["the paths of"]},
  "راهی": {"say": "raa-hay", "mean": ["the path that, a way"]},
  "ربطی": {"say": "rab-tay", "mean": ["connection", "هیچ ربطی: no connection"]},
  "رحیم": {"say": "ra-heem", "mean": ["Rahim, a name"]},
  "رد": {"say": "rad", "mean": ["track, trace", "رد پای: footprints"]},
  "رسید": {"say": "ra-seed", "mean": ["arrived, reached"]},
  "رفت": {"say": "raft", "mean": ["went"]},
  "رفتم": {"say": "raf-tum", "mean": ["I went"]},
  "رفتن": {"say": "raf-tan", "mean": ["they went", "going"]},
  "رفتنش": {"say": "raf-ta-nish", "mean": ["his leaving"]},
  "رفتن‌شان": {"say": "raf-tan-shaan", "mean": ["their leaving"]},
  "رفته": {"say": "raf-ta", "mean": ["gone", "رفته نمی‌تانست: couldn't go"]},
  "رفتیم": {"say": "raf-taym", "mean": ["we went"]},
  "رقم": {"say": "ra-qam", "mean": ["kind, type", "ای رقم: this kind of"]},
  "رنگ": {"say": "rang", "mean": ["paint", "colour", "رنگ کدن: to paint"]},
  "رواج": {"say": "ra-waaj", "mean": ["custom, tradition"]},
  "روان": {"say": "ra-waan", "mean": ["sent off, going", "روان کدن: to send"]},
  "روباها": {"say": "ro-baa-haa", "mean": ["foxes"]},
  "روبای": {"say": "ro-baa-yay", "mean": ["a fox"]},
  "روز": {"say": "roz", "mean": ["day"]},
  "روشنی": {"say": "raw-sha-nee", "mean": ["light"]},
  "روشنی‌ها": {"say": "raw-sha-nee-haa", "mean": ["lights"]},
  "روی": {"say": "roo-yi", "mean": ["face", "on"]},
  "رویش": {"say": "roo-yish", "mean": ["his face"]},
  "ره": {"say": "ra", "mean": ["marks the object of a verb", "there is no English word for it"]},
  "ریخته": {"say": "raykh-ta", "mean": ["spilled", "ریخته باشه: has been spilled"]},
  "زانوهایش": {"say": "zaa-noo-haa-yish", "mean": ["her knees"]},
  "زدن": {"say": "za-dan", "mean": ["hitting", "گپ زدن: talking"]},
  "زده": {"say": "za-da", "mean": ["hit", "صدمه زده نمی‌تانه: can't hurt"]},
  "زردآلو": {"say": "zard-aa-loo", "mean": ["apricot"]},
  "زردآلوی": {"say": "zard-aa-loo-yi", "mean": ["the apricot trees of"]},
  "زمستان": {"say": "zi-mis-taan", "mean": ["winter"]},
  "زمستانی": {"say": "zi-mis-taa-nay", "mean": ["the winter that"]},
  "زمین": {"say": "za-meen", "mean": ["land, field", "ground"]},
  "زمینش": {"say": "za-mee-nish", "mean": ["his land"]},
  "زمین‌ها": {"say": "za-meen-haa", "mean": ["fields"]},
  "زمین‌های": {"say": "za-meen-haay", "mean": ["the lands, the fields of"]},
  "زن": {"say": "zan", "mean": ["woman", "wife"]},
  "زندگی": {"say": "zin-da-gee", "mean": ["life", "زندگی کدن: to live"]},
  "زنده": {"say": "zin-da", "mean": ["alive"]},
  "زن‌ها": {"say": "zan-haa", "mean": ["women"]},
  "زن‌های": {"say": "zan-haay", "mean": ["the women of"]},
  "زن‌هایی": {"say": "zan-haa-yay", "mean": ["women who"]},
  "زنی": {"say": "za-nay", "mean": ["a woman who"]},
  "زیاد": {"say": "zi-yaad", "mean": ["a lot, much, many"]},
  "زیادتر": {"say": "zi-yaad-tar", "mean": ["more"]},
  "زیادتری": {"say": "zi-yaad-ta-ray", "mean": ["more people"]},
  "زیادی": {"say": "zi-yaa-day", "mean": ["many, a lot of"]},
  "زیارت": {"say": "zi-yaa-rat", "mean": ["shrine"]},
  "زیر": {"say": "zayr", "mean": ["under"]},
  "زین": {"say": "zayn", "mean": ["saddle"]},
  "زینب": {"say": "zay-nab", "mean": ["Zainab, a name"]},
  "زینه": {"say": "zee-na", "mean": ["step, stairs"]},
  "ساعت": {"say": "saa-at", "mean": ["watch, clock", "hour"]},
  "سال": {"say": "saal", "mean": ["year"]},
  "سال‌ها": {"say": "saal-haa", "mean": ["years"]},
  "سالی": {"say": "saa-lay", "mean": ["the year that"]},
  "سبز": {"say": "sabz", "mean": ["green", "سبز شدن: to grow"]},
  "سخت": {"say": "sakht", "mean": ["hard, difficult"]},
  "سر": {"say": "sar", "mean": ["head", "on, on top of", "at"]},
  "سرخ": {"say": "surkh", "mean": ["red"]},
  "سرد": {"say": "sard", "mean": ["cold"]},
  "سردی": {"say": "sar-dee", "mean": ["the cold"]},
  "سرش": {"say": "sa-rish", "mean": ["on it, over it"]},
  "سرک": {"say": "sa-rak", "mean": ["road"]},
  "سفید": {"say": "sa-fayd", "mean": ["white"]},
  "سکه": {"say": "sik-ka", "mean": ["coin"]},
  "سکه‌های": {"say": "sik-ka-haay", "mean": ["the coins of"]},
  "سکینه": {"say": "sa-kee-na", "mean": ["Sakina, a name"]},
  "سگ": {"say": "sag", "mean": ["dog"]},
  "سگ‌ها": {"say": "sag-haa", "mean": ["the dogs"]},
  "سلام": {"say": "sa-laam", "mean": ["greeting, hello", "سلام کدن: to greet"]},
  "سنگ": {"say": "sang", "mean": ["stone"]},
  "سنگرهای": {"say": "san-gar-haay", "mean": ["the positions, the trenches of"]},
  "سنگ‌های": {"say": "sang-haay", "mean": ["stones"]},
  "سنگین": {"say": "san-geen", "mean": ["heavy"]},
  "سوال": {"say": "sa-waal", "mean": ["question"]},
  "سوال‌ها": {"say": "sa-waal-haa", "mean": ["questions"]},
  "سوال‌هایی": {"say": "sa-waal-haa-yay", "mean": ["questions that"]},
  "سوختاند": {"say": "sokh-taand", "mean": ["burned something"]},
  "سوختاندم": {"say": "sokh-taan-dum", "mean": ["I burned"]},
  "سودا": {"say": "saw-daa", "mean": ["trade, selling", "سودا کدن: to sell"]},
  "سوراخ": {"say": "soo-raakh", "mean": ["hole"]},
  "سوم": {"say": "sa-wum", "mean": ["third"]},
  "سه": {"say": "say", "mean": ["three"]},
  "سیاه": {"say": "si-yaa", "mean": ["black"]},
  "سیل": {"say": "sayl", "mean": ["look", "سیل کدن: to look, to watch"]},
  "شاخه‌های": {"say": "shaa-kha-haay", "mean": ["the branches of"]},
  "شام": {"say": "shaam", "mean": ["evening"]},
  "شاه": {"say": "shaah", "mean": ["king, Shah"]},
  "شاید": {"say": "shaa-yad", "mean": ["maybe, perhaps"]},
  "شبی": {"say": "sha-bay", "mean": ["the night that"]},
  "شد": {"say": "shud", "mean": ["became", "happened", "started"]},
  "شدم": {"say": "shu-dum", "mean": ["I became"]},
  "شدن": {"say": "shu-dan", "mean": ["they became", "becoming", "تمام شدن: they ended"]},
  "شده": {"say": "shu-da", "mean": ["has become", "had been"]},
  "شروع": {"say": "shu-roo", "mean": ["start", "شروع کدن: to begin"]},
  "شستن": {"say": "shus-tan", "mean": ["washing"]},
  "شش": {"say": "shash", "mean": ["six"]},
  "شکست": {"say": "shi-kast", "mean": ["broke"]},
  "شکل": {"say": "shakl", "mean": ["shape, way"]},
  "شکوفه": {"say": "shi-ko-fa", "mean": ["blossom", "شکوفه کدن: to blossom"]},
  "شمال": {"say": "sha-maal", "mean": ["north", "wind"]},
  "شنبه": {"say": "sham-ba", "mean": ["Saturday", "سه شنبه: Tuesday"]},
  "شنید": {"say": "shu-need", "mean": ["heard"]},
  "شنیدم": {"say": "shu-nee-dum", "mean": ["I heard"]},
  "شنیدن": {"say": "shu-nee-dan", "mean": ["they heard", "hearing"]},
  "شنیده": {"say": "shu-nee-da", "mean": ["had heard"]},
  "شو": {"say": "shaw", "mean": ["night"]},
  "شوا": {"say": "sha-waa", "mean": ["at night, nights"]},
  "شور": {"say": "shor", "mean": ["movement", "شور خوردن: to move"]},
  "شوم": {"say": "sha-wum", "mean": ["that I become", "دفن شوم: that I be buried"]},
  "شوه": {"say": "sha-wa", "mean": ["becomes, is", "that she be"]},
  "شوهر": {"say": "shaw-har", "mean": ["husband"]},
  "شوهرم": {"say": "shaw-ha-rum", "mean": ["my husband"]},
  "شهر": {"say": "shahr", "mean": ["city"]},
  "شیر": {"say": "sheer", "mean": ["milk"]},
  "شیرین": {"say": "shee-reen", "mean": ["Shirin, a name"]},
  "شیرینی": {"say": "shee-ree-nee", "mean": ["sweets"]},
  "شیشت": {"say": "shisht", "mean": ["sat"]},
  "شیشتم": {"say": "shish-tum", "mean": ["I sat"]},
  "صاحب": {"say": "saa-hib", "mean": ["owner"]},
  "صاحبش": {"say": "saa-hi-bish", "mean": ["its owner"]},
  "صبا": {"say": "sa-baa", "mean": ["tomorrow"]},
  "صبح": {"say": "subh", "mean": ["morning"]},
  "صبر": {"say": "sabr", "mean": ["patience, waiting", "صبر کدن: to wait"]},
  "صدا": {"say": "sa-daa", "mean": ["voice, sound", "صدا کدن: to call"]},
  "صداها": {"say": "sa-daa-haa", "mean": ["sounds, noises"]},
  "صداهای": {"say": "sa-daa-haay", "mean": ["voices, sounds"]},
  "صدای": {"say": "sa-daa-yi", "mean": ["the sound of"]},
  "صدمه": {"say": "sad-ma", "mean": ["harm", "صدمه زدن: to hurt"]},
  "صف": {"say": "saf", "mean": ["row, line"]},
  "صلح": {"say": "sulh", "mean": ["peace", "صلح کدن: to make peace"]},
  "طرف": {"say": "ta-raf", "mean": ["toward", "side"]},
  "طرفم": {"say": "ta-ra-fum", "mean": ["toward me, at me"]},
  "طفل": {"say": "tifl", "mean": ["child"]},
  "طفلا": {"say": "tif-laa", "mean": ["children"]},
  "طفل‌ها": {"say": "tifl-haa", "mean": ["children"]},
  "طفل‌های": {"say": "tifl-haay", "mean": ["the children of"]},
  "طفل‌هایم": {"say": "tifl-haa-yum", "mean": ["my children"]},
  "ظاهر": {"say": "zaa-hir", "mean": ["Zahir", "ظاهر شاه: King Zahir Shah"]},
  "عبدالقادر": {"say": "ab-dul-qaa-dir", "mean": ["Abdul Qadir, a name"]},
  "عجیب": {"say": "a-jeeb", "mean": ["strange"]},
  "عروس": {"say": "a-roos", "mean": ["bride"]},
  "عروسی": {"say": "a-roo-see", "mean": ["wedding", "عروسی کدن: to marry"]},
  "عقل": {"say": "aql", "mean": ["mind, reason"]},
  "علف": {"say": "a-laf", "mean": ["grass"]},
  "علفی": {"say": "a-la-fay", "mean": ["any grass", "هیچ علفی: no grass"]},
  "عمه‌ام": {"say": "am-ma-um", "mean": ["my aunt, father's sister"]},
  "غپیدن": {"say": "gha-pee-dan", "mean": ["they barked"]},
  "غله": {"say": "ghal-la", "mean": ["grain"]},
  "فامید": {"say": "faa-meed", "mean": ["found out, learned"]},
  "فامیل": {"say": "faa-meel", "mean": ["family"]},
  "فامیلم": {"say": "faa-mee-lum", "mean": ["my family"]},
  "فامیل‌ها": {"say": "faa-meel-haa", "mean": ["families"]},
  "فامیل‌های": {"say": "faa-meel-haay", "mean": ["the families of"]},
  "فامیل‌هایی": {"say": "faa-meel-haa-yay", "mean": ["families that"]},
  "فامیلی": {"say": "faa-mee-lay", "mean": ["a family that"]},
  "فراموش": {"say": "fa-raa-mosh", "mean": ["forgotten", "فراموش کدن: to forget"]},
  "فرید": {"say": "fa-reed", "mean": ["Farid, a name"]},
  "فقط": {"say": "fa-qat", "mean": ["only"]},
  "فکر": {"say": "fikr", "mean": ["thought", "فکر کدن: to think"]},
  "قات": {"say": "qaat", "mean": ["folded", "قات شده: folded"]},
  "قادر": {"say": "qaa-dir", "mean": ["Qadir, a name"]},
  "قار": {"say": "qaar", "mean": ["angry"]},
  "قبر": {"say": "qabr", "mean": ["grave"]},
  "قبرستان": {"say": "qab-ris-taan", "mean": ["cemetery"]},
  "قبرش": {"say": "qab-rish", "mean": ["her grave"]},
  "قبرهای": {"say": "qabr-haay", "mean": ["the graves of"]},
  "قدر": {"say": "qadr", "mean": ["amount, as much"]},
  "قدم": {"say": "qa-dam", "mean": ["step", "قدم زدن: to walk"]},
  "قدیم": {"say": "qa-deem", "mean": ["old times, former"]},
  "قدیمی‌ها": {"say": "qa-dee-mee-haa", "mean": ["the old ones"]},
  "قرآن": {"say": "qur-aan", "mean": ["the Quran"]},
  "قریه": {"say": "qar-ya", "mean": ["village"]},
  "قصه": {"say": "qis-sa", "mean": ["story"]},
  "قطار": {"say": "qa-taar", "mean": ["row, line"]},
  "قطع": {"say": "qat", "mean": ["cut", "قطع کدن: to cut"]},
  "قطی": {"say": "qu-tee", "mean": ["tin box, box"]},
  "قوماندانم": {"say": "qo-maan-daa-num", "mean": ["my commander"]},
  "قوی": {"say": "qa-wee", "mean": ["strong"]},
  "قوی‌تر": {"say": "qa-wee-tar", "mean": ["stronger"]},
  "کابل": {"say": "kaa-bul", "mean": ["Kabul, a city"]},
  "کاپی": {"say": "kaa-pee", "mean": ["copy"]},
  "کاپیش": {"say": "kaa-peesh", "mean": ["its copy"]},
  "کار": {"say": "kaar", "mean": ["work, job", "thing to do", "کار داشتن: to need"]},
  "کارش": {"say": "kaa-rish", "mean": ["need it", "کارش نداشت: didn't need it"]},
  "کاغذ": {"say": "kaa-ghaz", "mean": ["paper, document"]},
  "کاغذها": {"say": "kaa-ghaz-haa", "mean": ["papers, documents"]},
  "کاغذهای": {"say": "kaa-ghaz-haay", "mean": ["the papers of"]},
  "کاکا": {"say": "kaa-kaa", "mean": ["uncle, father's brother", "بچه کاکا: cousin"]},
  "کاکای": {"say": "kaa-kaa-yi", "mean": ["uncle of", "بچه کاکای: the cousin of"]},
  "کاکایم": {"say": "kaa-kaa-yum", "mean": ["my uncle, father's brother"]},
  "کالایش": {"say": "kaa-laa-yish", "mean": ["his clothes"]},
  "کتابچه": {"say": "ki-taab-cha", "mean": ["notebook"]},
  "کتابچه‌اش": {"say": "ki-taab-cha-ash", "mean": ["her notebook"]},
  "کتابچه‌ام": {"say": "ki-taab-cha-um", "mean": ["my notebook"]},
  "کجا": {"say": "ku-jaa", "mean": ["where"]},
  "کد": {"say": "kad", "mean": ["he or she did, made", "پرسان کد: asked"]},
  "کدام": {"say": "ku-daam", "mean": ["which"]},
  "کدم": {"say": "ka-dum", "mean": ["I did"]},
  "کدن": {"say": "ka-dan", "mean": ["they did", "doing"]},
  "کده": {"say": "ka-da", "mean": ["has done", "از ... کده: than"]},
  "کدیم": {"say": "ka-daym", "mean": ["we did"]},
  "کسایی": {"say": "ka-saa-yee", "mean": ["people who, those who"]},
  "کسی": {"say": "ka-say", "mean": ["someone, anyone"]},
  "کشمش‌های": {"say": "kish-mish-haay", "mean": ["the raisins of"]},
  "کشیده": {"say": "ka-shee-da", "mean": ["pulled out", "بیرون کشیده بود: had pulled out"]},
  "کلان": {"say": "ka-laan", "mean": ["big, large"]},
  "کلان‌تر": {"say": "ka-laan-tar", "mean": ["older, bigger"]},
  "کلاه": {"say": "ku-laa", "mean": ["cap, hat"]},
  "کلکین": {"say": "kil-keen", "mean": ["window"]},
  "کلمه": {"say": "ka-li-ma", "mean": ["word"]},
  "کمپل": {"say": "kam-pal", "mean": ["blanket"]},
  "کمپل‌ها": {"say": "kam-pal-haa", "mean": ["blankets"]},
  "کمپل‌های": {"say": "kam-pal-haay", "mean": ["the blankets of"]},
  "کمک": {"say": "ku-mak", "mean": ["help"]},
  "کمی": {"say": "ka-may", "mean": ["a little"]},
  "کند": {"say": "kand", "mean": ["dug"]},
  "کندم": {"say": "kan-dum", "mean": ["I dug"]},
  "کندوهای": {"say": "kan-doo-haay", "mean": ["the pits of"]},
  "کندوی": {"say": "kan-doo-yi", "mean": ["a pit of", "کندوی غله: grain pit"]},
  "کنده": {"say": "kan-da", "mean": ["dug", "کنده شده: dug up"]},
  "کنم": {"say": "ku-num", "mean": ["that I do"]},
  "کنن": {"say": "ku-nan", "mean": ["that they do"]},
  "کنه": {"say": "ku-na", "mean": ["that he/she does"]},
  "کنیم": {"say": "ku-naym", "mean": ["that we do"]},
  "کوچه": {"say": "koo-cha", "mean": ["lane, street"]},
  "کوزه‌های": {"say": "ko-za-haay", "mean": ["jars of"]},
  "کوشش": {"say": "ko-shish", "mean": ["effort, trying", "کوشش کدن: to try"]},
  "کوه": {"say": "koh", "mean": ["mountain"]},
  "کوه‌ها": {"say": "koh-haa", "mean": ["mountains, the hills"]},
  "که": {"say": "ki", "mean": ["that, which, who"]},
  "کهنه": {"say": "koh-na", "mean": ["old", "Kohna, the old, empty part of the village"]},
  "کهنه‌تر": {"say": "koh-na-tar", "mean": ["older"]},
  "کی": {"say": "kee", "mean": ["who"]},
  "گپ": {"say": "gap", "mean": ["talk, words", "گپ زدن: to talk"]},
  "گپا": {"say": "ga-paa", "mean": ["words, talk, things people say"]},
  "گپش": {"say": "ga-pish", "mean": ["his words", "گپش ره گوش کد: listened to him"]},
  "گپی": {"say": "ga-pay", "mean": ["a word, any word", "بی هیچ گپی: without a word"]},
  "گدام": {"say": "gu-daam", "mean": ["storeroom"]},
  "گدام‌های": {"say": "gu-daam-haay", "mean": ["the storerooms of"]},
  "گذشته": {"say": "gu-zash-ta", "mean": ["last, past", "هفته گذشته: last week"]},
  "گرفت": {"say": "gi-rift", "mean": ["took, got", "نام گرفت: said a name"]},
  "گرفتم": {"say": "gi-rif-tum", "mean": ["I took", "تصمیم گرفتم: I decided"]},
  "گرم": {"say": "garm", "mean": ["warm"]},
  "گروپ": {"say": "groop", "mean": ["group"]},
  "گریه": {"say": "gir-ya", "mean": ["crying", "گریه کدن: to cry"]},
  "گشنه": {"say": "gush-na", "mean": ["hungry"]},
  "گفت": {"say": "guft", "mean": ["said, told"]},
  "گفتم": {"say": "guf-tum", "mean": ["I said, I told"]},
  "گفتن": {"say": "guf-tan", "mean": ["they said"]},
  "گفته": {"say": "guf-ta", "mean": ["has said, had told"]},
  "گل": {"say": "gil", "mean": ["mud"]},
  "گلشان": {"say": "gil-shaan", "mean": ["their mud"]},
  "گلی": {"say": "gi-lee", "mean": ["clay"]},
  "گم": {"say": "gum", "mean": ["lost, missing", "گم بودن: to be missing"]},
  "گندم": {"say": "gan-dum", "mean": ["wheat"]},
  "گندم‌ها": {"say": "gan-dum-haa", "mean": ["the wheat"]},
  "گوش": {"say": "gosh", "mean": ["ear", "گوش کدن: to listen"]},
  "لطیف": {"say": "la-teef", "mean": ["Latif, a name"]},
  "ما": {"say": "maa", "mean": ["we, us", "our"]},
  "مادر": {"say": "maa-dar", "mean": ["mother"]},
  "مادرا": {"say": "maa-da-raa", "mean": ["mothers"]},
  "مادراشان": {"say": "maa-da-raa-shaan", "mean": ["their mothers"]},
  "مادرش": {"say": "maa-da-rish", "mean": ["his/her mother"]},
  "مادرشان": {"say": "maa-dar-shaan", "mean": ["their mother"]},
  "مادرکلان": {"say": "maa-dar-ka-laan", "mean": ["grandmother"]},
  "مادرکلانم": {"say": "maa-dar-ka-laa-num", "mean": ["my grandmother"]},
  "مادرم": {"say": "maa-da-rum", "mean": ["my mother"]},
  "مادری": {"say": "maa-da-ray", "mean": ["a mother who"]},
  "مارها": {"say": "maar-haa", "mean": ["snakes"]},
  "مالیه": {"say": "maa-li-ya", "mean": ["tax"]},
  "ماما": {"say": "maa-maa", "mean": ["uncle, mother's brother"]},
  "ماماهاشان": {"say": "maa-maa-haa-shaan", "mean": ["their uncles, mother's brothers"]},
  "ماند": {"say": "maand", "mean": ["put, left, placed", "stayed", "let", "نماند: didn't let"]},
  "ماندم": {"say": "maan-dum", "mean": ["I put, I placed"]},
  "ماندن": {"say": "maan-dan", "mean": ["they put, they placed"]},
  "مانده": {"say": "maan-da", "mean": ["tired"]},
  "ماندیم": {"say": "maan-daym", "mean": ["we put, we placed"]},
  "ماه": {"say": "maah", "mean": ["month", "moon"]},
  "ماه‌ها": {"say": "maah-haa", "mean": ["months"]},
  "ماین": {"say": "maa-yin", "mean": ["mine, landmine"]},
  "ماین‌پاک‌ها": {"say": "maa-yin-paak-haa", "mean": ["the mine clearers"]},
  "ماین‌پاک‌های": {"say": "maa-yin-paak-haay", "mean": ["the mine clearers of"]},
  "ماین‌ها": {"say": "maa-yin-haa", "mean": ["the mines"]},
  "مثل": {"say": "mi-sil", "mean": ["like, as"]},
  "مجاهدین": {"say": "mu-jaa-hi-deen", "mean": ["the mujahideen, fighters against the Soviets"]},
  "مرد": {"say": "mard (died: murd)", "mean": ["man", "died"]},
  "مردا": {"say": "mar-daa", "mean": ["the men"]},
  "مردای": {"say": "mar-daa-yi", "mean": ["men of"]},
  "مردایی": {"say": "mar-daa-yay", "mean": ["men who"]},
  "مردم": {"say": "mar-dum", "mean": ["people"]},
  "مردن": {"say": "mur-dan", "mean": ["dying, death", "پیش از مردن: before dying"]},
  "مردنش": {"say": "mur-da-nish", "mean": ["her death, his death"]},
  "مرده": {"say": "mur-da", "mean": ["dead"]},
  "مردی": {"say": "mar-day", "mean": ["the man who"]},
  "مرگ": {"say": "marg", "mean": ["death"]},
  "مریض": {"say": "ma-reez", "mean": ["sick, ill"]},
  "مریم": {"say": "mar-yam", "mean": ["Maryam, a name"]},
  "مسافرا": {"say": "mu-saa-fi-raa", "mean": ["travellers"]},
  "مسجد": {"say": "mas-jid", "mean": ["mosque"]},
  "مسلمان": {"say": "mu-sul-maan", "mean": ["Muslim, believer"]},
  "مشکل": {"say": "mush-kil", "mean": ["problem"]},
  "مشهد": {"say": "mash-had", "mean": ["Mashhad, a city in Iran"]},
  "مصروف": {"say": "mas-roof", "mean": ["busy"]},
  "مطمئن": {"say": "mut-ma-in", "mean": ["sure"]},
  "مکتب": {"say": "mak-tab", "mean": ["school"]},
  "مکتوب": {"say": "mak-toob", "mean": ["letter"]},
  "منتظر": {"say": "mun-ta-zir", "mean": ["waiting", "منتظر ماندن: to wait"]},
  "منتظرش": {"say": "mun-ta-zi-rish", "mean": ["waiting for him"]},
  "موافق": {"say": "mu-waa-fiq", "mean": ["agreeing, in agreement"]},
  "موسم": {"say": "maw-sim", "mean": ["season"]},
  "مه": {"say": "ma", "mean": ["I, me"]},
  "مهربان": {"say": "meh-ra-baan", "mean": ["kind"]},
  "مهمان‌ها": {"say": "meh-maan-haa", "mean": ["guests, visitors"]},
  "میاره": {"say": "may-yaa-ra", "mean": ["brings"]},
  "می‌انداختم": {"say": "may-an-daakh-tum", "mean": ["I used to throw"]},
  "می‌آمد": {"say": "may-aa-mad", "mean": ["used to come"]},
  "می‌آمدن": {"say": "may-aa-ma-dan", "mean": ["used to come, came"]},
  "می‌آیم": {"say": "may-aa-yum", "mean": ["I come"]},
  "می‌آین": {"say": "may-aa-yan", "mean": ["they come"]},
  "می‌آیه": {"say": "may-aa-ya", "mean": ["comes"]},
  "می‌باره": {"say": "may-baa-ra", "mean": ["is falling, of rain or snow"]},
  "می‌بارید": {"say": "may-baa-reed", "mean": ["was raining, was falling"]},
  "می‌برد": {"say": "may-burd", "mean": ["used to take, carried"]},
  "می‌برم": {"say": "may-ba-rum", "mean": ["I take"]},
  "می‌برن": {"say": "may-ba-ran", "mean": ["they take, they carry off"]},
  "می‌بود": {"say": "may-bood", "mean": ["were, would be"]},
  "می‌بینم": {"say": "may-bee-num", "mean": ["I see"]},
  "می‌بینه": {"say": "may-bee-na", "mean": ["sees"]},
  "می‌تانن": {"say": "may-taa-nan", "mean": ["they can"]},
  "می‌تانه": {"say": "may-taa-na", "mean": ["can, is able"]},
  "می‌تانیم": {"say": "may-taa-naym", "mean": ["we can"]},
  "می‌تانین": {"say": "may-taa-nayn", "mean": ["you can, the polite form"]},
  "می‌ترسید": {"say": "may-tar-seed", "mean": ["was afraid"]},
  "می‌چید": {"say": "may-cheed", "mean": ["used to pick"]},
  "می‌خایم": {"say": "may-khaa-yum", "mean": ["I want"]},
  "می‌خاین": {"say": "may-khaa-yan", "mean": ["they want"]},
  "می‌خایه": {"say": "may-khaa-ya", "mean": ["wants"]},
  "می‌خواست": {"say": "may-khaast", "mean": ["wanted"]},
  "می‌خواستم": {"say": "may-khaas-tum", "mean": ["I wanted"]},
  "می‌خواستن": {"say": "may-khaas-tan", "mean": ["they wanted"]},
  "می‌خوانم": {"say": "may-khaa-num", "mean": ["I read, I will read aloud"]},
  "می‌خوانه": {"say": "may-khaa-na", "mean": ["reads"]},
  "می‌خورد": {"say": "may-khord", "mean": ["used to eat"]},
  "می‌خوردن": {"say": "may-khor-dan", "mean": ["they were eating", "خنک می‌خوردن: they were cold"]},
  "می‌داد": {"say": "may-daad", "mean": ["used to give"]},
  "می‌داشت": {"say": "may-daasht", "mean": ["used to hold", "نگاه می‌داشت: held"]},
  "میده": {"say": "may-da", "mean": ["gives"]},
  "می‌دیدیم": {"say": "may-dee-daym", "mean": ["we used to see"]},
  "می‌رفت": {"say": "may-raft", "mean": ["used to go, was going"]},
  "می‌رفتیم": {"say": "may-raf-taym", "mean": ["we used to go"]},
  "میرن": {"say": "may-ran", "mean": ["they go, they're going"]},
  "میره": {"say": "may-ra", "mean": ["goes, is going"]},
  "می‌زد": {"say": "may-zad", "mean": ["was hitting", "قدم می‌زد: was walking"]},
  "می‌زنن": {"say": "may-za-nan", "mean": ["they hit", "گپ می‌زنن: they talk"]},
  "می‌زنه": {"say": "may-za-na", "mean": ["hits", "گپ می‌زنه: talks"]},
  "می‌شدن": {"say": "may-shu-dan", "mean": ["used to become", "گم می‌شدن: got lost"]},
  "میشم": {"say": "may-shum", "mean": ["I become", "تیر میشم: I cross over"]},
  "میشن": {"say": "may-shan", "mean": ["they become"]},
  "می‌شناخت": {"say": "may-shi-naakht", "mean": ["knew a person"]},
  "می‌شناختم": {"say": "may-shi-naakh-tum", "mean": ["I knew a person"]},
  "می‌شناختن": {"say": "may-shi-naakh-tan", "mean": ["they knew people"]},
  "می‌شناسم": {"say": "may-shi-naa-sum", "mean": ["I know, I recognize"]},
  "می‌شنوم": {"say": "maysh-na-wum", "mean": ["I hear"]},
  "می‌شنون": {"say": "maysh-na-wan", "mean": ["they hear"]},
  "میشه": {"say": "may-sha", "mean": ["becomes, gets", "happens"]},
  "می‌شیشت": {"say": "may-shisht", "mean": ["used to sit"]},
  "می‌غپن": {"say": "may-gha-pan", "mean": ["they bark"]},
  "می‌غپه": {"say": "may-gha-pa", "mean": ["barks"]},
  "می‌فامم": {"say": "may-faa-mum", "mean": ["I know, I understand"]},
  "می‌فامن": {"say": "may-faa-man", "mean": ["they know, they understand"]},
  "می‌فامه": {"say": "may-faa-ma", "mean": ["knows"]},
  "می‌فامید": {"say": "may-faa-meed", "mean": ["would know", "knew"]},
  "می‌فامیدن": {"say": "may-faa-mee-dan", "mean": ["they knew"]},
  "می‌کد": {"say": "may-kad", "mean": ["he or she used to do", "he or she was doing"]},
  "می‌کدم": {"say": "may-ka-dum", "mean": ["I used to do"]},
  "می‌کدن": {"say": "may-ka-dan", "mean": ["they used to do"]},
  "می‌کدیم": {"say": "may-ka-daym", "mean": ["we used to do"]},
  "می‌کنم": {"say": "may-ku-num", "mean": ["I do, I make"]},
  "می‌کنن": {"say": "may-ku-nan", "mean": ["they do, they make"]},
  "می‌کنه": {"say": "may-ku-na", "mean": ["he or she does, makes"]},
  "می‌گردم": {"say": "may-gar-dum", "mean": ["I walk around, I go about"]},
  "می‌گردن": {"say": "may-gar-dan", "mean": ["they go around", "پس کسی گشتن: to follow someone"]},
  "می‌گرده": {"say": "may-gar-da", "mean": ["looks around", "پس چیزی گشتن: to look for something"]},
  "می‌گشت": {"say": "may-gasht", "mean": ["used to go around", "پس کسی گشتن: to follow someone"]},
  "می‌گفت": {"say": "may-guft", "mean": ["used to say, was saying"]},
  "می‌گفتن": {"say": "may-guf-tan", "mean": ["they used to say"]},
  "می‌گفتیم": {"say": "may-guf-taym", "mean": ["we used to say"]},
  "میگم": {"say": "may-gum", "mean": ["I say, I tell"]},
  "میگن": {"say": "may-gan", "mean": ["they say"]},
  "میگه": {"say": "may-ga", "mean": ["says, he/she says"]},
  "می‌گیرم": {"say": "may-gee-rum", "mean": ["I take", "تصمیم می‌گیرم: I decide"]},
  "می‌گیره": {"say": "may-gee-ra", "mean": ["takes, gets"]},
  "می‌گیریم": {"say": "may-gee-raym", "mean": ["we take", "کار می‌گیریم: we use"]},
  "می‌ماند": {"say": "may-maand", "mean": ["would let", "would leave"]},
  "می‌ماندن": {"say": "may-maan-dan", "mean": ["used to stay, used to wait"]},
  "می‌مانن": {"say": "may-maa-nan", "mean": ["they stay"]},
  "می‌مانه": {"say": "may-maa-na", "mean": ["stays", "puts", "lets"]},
  "می‌نوشه": {"say": "may-no-sha", "mean": ["drinks"]},
  "میوه‌شه": {"say": "may-wa-sha", "mean": ["its fruit"]},
  "نام": {"say": "naam", "mean": ["name"]},
  "نامد": {"say": "naa-mad", "mean": ["didn't come"]},
  "نامش": {"say": "naa-mish", "mean": ["his/her name"]},
  "نامم": {"say": "naa-mum", "mean": ["my name"]},
  "نام‌ها": {"say": "naam-haa", "mean": ["names"]},
  "نام‌های": {"say": "naam-haay", "mean": ["the names of"]},
  "نام‌هایشان": {"say": "naam-haa-yi-shaan", "mean": ["their names"]},
  "نامی": {"say": "naa-may", "mean": ["a name, any name"]},
  "نان": {"say": "naan", "mean": ["bread", "a meal"]},
  "ناوخت": {"say": "naa-wakht", "mean": ["late"]},
  "نباید": {"say": "na-baa-yad", "mean": ["shouldn't, must not"]},
  "نبود": {"say": "na-bood", "mean": ["wasn't", "wasn't there"]},
  "نبودم": {"say": "na-boo-dum", "mean": ["I wasn't"]},
  "نبودن": {"say": "na-boo-dan", "mean": ["they weren't", "they weren't there"]},
  "نبوده": {"say": "na-boo-da", "mean": ["wasn't, there wasn't"]},
  "نبی": {"say": "na-bee", "mean": ["Nabi, a name"]},
  "نتانست": {"say": "na-taa-nist", "mean": ["couldn't"]},
  "نتم": {"say": "na-tum", "mean": ["that I don't give", "جواب نتم: that I not answer"]},
  "نخواست": {"say": "na-khaast", "mean": ["didn't want"]},
  "ندادم": {"say": "na-daa-dum", "mean": ["I didn't give", "جواب ندادم: I didn't answer"]},
  "ندادن": {"say": "na-daa-dan", "mean": ["they didn't give"]},
  "نداده": {"say": "na-daa-da", "mean": ["hasn't given", "یاد نداده: hasn't taught"]},
  "ندارن": {"say": "na-daa-ran", "mean": ["they don't have"]},
  "نداره": {"say": "na-daa-ra", "mean": ["doesn't have", "doesn't need"]},
  "نداشت": {"say": "na-daasht", "mean": ["didn't have"]},
  "نداشتن": {"say": "na-daash-tan", "mean": ["they didn't have"]},
  "ندید": {"say": "na-deed", "mean": ["didn't see"]},
  "ندیدم": {"say": "na-dee-dum", "mean": ["I didn't see", "I haven't seen"]},
  "ندیده": {"say": "na-dee-da", "mean": ["hadn't seen"]},
  "نرفتم": {"say": "na-raf-tum", "mean": ["I didn't go"]},
  "نرم": {"say": "narm", "mean": ["soft"]},
  "نرن": {"say": "na-ran", "mean": ["that they don't go"]},
  "نره": {"say": "na-ra", "mean": ["that he doesn't go"]},
  "نزد": {"say": "na-zad", "mean": ["didn't hit", "گپ نزد: didn't speak"]},
  "نزدیک": {"say": "naz-deek", "mean": ["near, close to"]},
  "نسوختاندم": {"say": "na-sokh-taan-dum", "mean": ["I didn't burn"]},
  "نسوختاندیم": {"say": "na-sokh-taan-daym", "mean": ["we didn't burn"]},
  "نشان": {"say": "ni-shaan", "mean": ["sign", "نشان دادن: to show"]},
  "نشانی": {"say": "ni-shaa-nay", "mean": ["mark, sign"]},
  "نشده": {"say": "na-shu-da", "mean": ["hasn't happened"]},
  "نشست": {"say": "ni-shast", "mean": ["sinking", "نشست کدن: to sink"]},
  "نشنیدم": {"say": "na-shu-nee-dum", "mean": ["I didn't hear"]},
  "نکد": {"say": "na-kad", "mean": ["didn't do"]},
  "نکدم": {"say": "na-ka-dum", "mean": ["I didn't do", "فکر نکدم: I didn't think"]},
  "نکدن": {"say": "na-ka-dan", "mean": ["they didn't do"]},
  "نکده": {"say": "na-ka-da", "mean": ["hasn't done, didn't do"]},
  "نکنن": {"say": "na-ku-nan", "mean": ["that they don't do"]},
  "نکنه": {"say": "na-ku-na", "mean": ["that he/she doesn't do"]},
  "نگاه": {"say": "ni-gaah", "mean": ["look", "keeping", "نگاه کدن: to keep, to look after"]},
  "نگاه‌شان": {"say": "ni-gaah-shaan", "mean": ["keep them", "نگاه‌شان کنم: that I keep them"]},
  "نگرفتم": {"say": "na-gi-rif-tum", "mean": ["I didn't take", "تصمیم نگرفتم: I haven't decided"]},
  "نگفت": {"say": "na-guft", "mean": ["didn't say"]},
  "نگفتم": {"say": "na-guf-tum", "mean": ["I didn't say"]},
  "نماز": {"say": "na-maaz", "mean": ["prayer, the daily prayers"]},
  "نماند": {"say": "na-maand", "mean": ["didn't let", "didn't put"]},
  "نمک": {"say": "na-mak", "mean": ["salt"]},
  "نمیارم": {"say": "na-may-yaa-rum", "mean": ["I don't bring"]},
  "نمیایه": {"say": "na-may-aa-ya", "mean": ["doesn't come", "یاد کسی نمیایه: nobody remembers"]},
  "نمی‌آیم": {"say": "na-may-aa-yum", "mean": ["I don't come"]},
  "نمی‌بینیم": {"say": "na-may-bee-naym", "mean": ["we don't see"]},
  "نمی‌تانست": {"say": "na-may-taa-nist", "mean": ["couldn't, wasn't able"]},
  "نمی‌تانه": {"say": "na-may-taa-na", "mean": ["can't"]},
  "نمی‌تانیم": {"say": "na-may-taa-naym", "mean": ["we can't"]},
  "نمی‌ترسانه": {"say": "na-may-tar-saa-na", "mean": ["doesn't frighten"]},
  "نمی‌چینه": {"say": "na-may-chee-na", "mean": ["doesn't pick"]},
  "نمی‌خایم": {"say": "na-may-khaa-yum", "mean": ["I don't want"]},
  "نمی‌خواستن": {"say": "na-may-khaas-tan", "mean": ["they didn't want"]},
  "نمی‌رفت": {"say": "na-may-raft", "mean": ["didn't go, wouldn't go"]},
  "نمی‌رفتیم": {"say": "na-may-raf-taym", "mean": ["we didn't go"]},
  "نمیره": {"say": "na-may-ra", "mean": ["doesn't go"]},
  "نمی‌زد": {"say": "na-may-zad", "mean": ["didn't use to hit", "گپ نمی‌زد: didn't talk"]},
  "نمی‌زنم": {"say": "na-may-za-num", "mean": ["I don't hit", "گپ نمی‌زنم: I don't talk"]},
  "نمی‌زنه": {"say": "na-may-za-na", "mean": ["doesn't hit", "گپ نمی‌زنه: doesn't talk"]},
  "نمی‌شدن": {"say": "na-may-shu-dan", "mean": ["wouldn't become", "تیر نمی‌شدن: wouldn't pass"]},
  "نمی‌شناخت": {"say": "na-may-shi-naakht", "mean": ["didn't know a person"]},
  "نمیشه": {"say": "na-may-sha", "mean": ["doesn't become", "doesn't grow"]},
  "نمی‌غپه": {"say": "na-may-gha-pa", "mean": ["doesn't bark"]},
  "نمی‌فامم": {"say": "na-may-faa-mum", "mean": ["I don't know"]},
  "نمی‌فامه": {"say": "na-may-faa-ma", "mean": ["doesn't know"]},
  "نمی‌کد": {"say": "na-may-kad", "mean": ["didn't use to do, wasn't doing"]},
  "نمی‌کدیم": {"say": "na-may-ka-daym", "mean": ["we didn't use to do"]},
  "نمی‌کشید": {"say": "na-may-ka-sheed", "mean": ["didn't take off", "never took off"]},
  "نمی‌کنم": {"say": "na-may-ku-num", "mean": ["I don't do", "خو نمی‌کنم: I don't sleep"]},
  "نمی‌کنن": {"say": "na-may-ku-nan", "mean": ["they don't do"]},
  "نمی‌کنه": {"say": "na-may-ku-na", "mean": ["he/she doesn't do"]},
  "نمی‌کنیم": {"say": "na-may-ku-naym", "mean": ["we don't do"]},
  "نمی‌گفت": {"say": "na-may-guft", "mean": ["didn't say, wouldn't say"]},
  "نمیگم": {"say": "na-may-gum", "mean": ["I don't say, I don't tell"]},
  "نمیگه": {"say": "na-may-ga", "mean": ["doesn't say"]},
  "نمی‌مانن": {"say": "na-may-maa-nan", "mean": ["they don't stay"]},
  "نمی‌مانه": {"say": "na-may-maa-na", "mean": ["doesn't stay", "doesn't let"]},
  "نو": {"say": "naw", "mean": ["new"]},
  "نوبت": {"say": "naw-bat", "mean": ["turn"]},
  "نوبتشه": {"say": "naw-ba-ti-sha", "mean": ["his turn"]},
  "نوشته": {"say": "na-wish-ta", "mean": ["written", "نوشته کدن: to write"]},
  "نوی": {"say": "na-way", "mean": ["new", "چیز نوی: something new"]},
  "نی": {"say": "nay", "mean": ["no"]},
  "نیامد": {"say": "na-yaa-mad", "mean": ["didn't come"]},
  "نیامدن": {"say": "na-yaa-ma-dan", "mean": ["they didn't come"]},
  "نیامده": {"say": "na-yaa-ma-da", "mean": ["hasn't come"]},
  "نیاورد": {"say": "na-yaa-ward", "mean": ["didn't bring"]},
  "نیست": {"say": "nayst", "mean": ["is not"]},
  "نیستن": {"say": "nays-tan", "mean": ["they aren't"]},
  "نیفتن": {"say": "na-yuf-tan", "mean": ["so that they don't fall"]},
  "و": {"say": "wa", "mean": ["and"]},
  "واز": {"say": "waaz", "mean": ["open"]},
  "وخت": {"say": "wakht", "mean": ["time", "when"]},
  "ورق‌هایش": {"say": "wa-raq-haa-yish", "mean": ["its pages"]},
  "وقت": {"say": "waqt", "mean": ["early", "time"]},
  "وقتی": {"say": "waq-tay", "mean": ["when"]},
  "هر": {"say": "har", "mean": ["every, each"]},
  "هرات": {"say": "hi-raat", "mean": ["Herat, a city"]},
  "هفته": {"say": "haf-ta", "mean": ["week"]},
  "هفته‌ها": {"say": "haf-ta-haa", "mean": ["weeks"]},
  "هم": {"say": "ham", "mean": ["also, too", "each other"]},
  "همراه": {"say": "ham-raa", "mean": ["with"]},
  "همراهش": {"say": "ham-raa-hish", "mean": ["with it, with him"]},
  "همرایش": {"say": "ham-raa-yish", "mean": ["with him/her"]},
  "همرایم": {"say": "ham-raa-yum", "mean": ["with me"]},
  "همسایه": {"say": "ham-saa-ya", "mean": ["neighbour"]},
  "همطو": {"say": "ham-to", "mean": ["like that, the same way", "also"]},
  "همگی": {"say": "ha-ma-gee", "mean": ["everyone, all"]},
  "همو": {"say": "ha-moo", "mean": ["that same, that very"]},
  "همونجه": {"say": "ha-moon-ja", "mean": ["right there, in that same place"]},
  "همی": {"say": "ha-mee", "mean": ["this same, just this", "همی قدر: just this much"]},
  "همیشه": {"say": "ha-may-sha", "mean": ["always"]},
  "هنوز": {"say": "ha-nooz", "mean": ["still, yet"]},
  "هوا": {"say": "ha-waa", "mean": ["air"]},
  "هوشیار": {"say": "hosh-yaar", "mean": ["clever"]},
  "هیچ": {"say": "haych", "mean": ["no, none", "any, as in «not any»"]},
  "هیچ‌جا": {"say": "haych-jaa", "mean": ["nowhere, anywhere"]},
  "هیچ‌کدام‌شان": {"say": "haych-ku-daam-shaan", "mean": ["none of them"]},
  "هیچ‌کس": {"say": "haych-kas", "mean": ["nobody, no one"]},
  "هیچ‌وخت": {"say": "haych-wakht", "mean": ["never"]},
  "یا": {"say": "yaa", "mean": ["or"]},
  "یاد": {"say": "yaad", "mean": ["memory", "به یاد داشتن: to remember", "یاد دادن: to teach"]},
  "یادشان": {"say": "yaad-shaan", "mean": ["their memory", "یادشان رفت: they forgot"]},
  "یادم": {"say": "yaa-dum", "mean": ["my memory", "یادم است: I remember"]},
  "یافت": {"say": "yaaft", "mean": ["found"]},
  "یافتم": {"say": "yaaf-tum", "mean": ["I found"]},
  "یافتن": {"say": "yaaf-tan", "mean": ["they found"]},
  "یافته": {"say": "yaaf-ta", "mean": ["had found"]},
  "یک": {"say": "yak", "mean": ["a, one"]},
  "یکجایی": {"say": "yak-jaa-yee", "mean": ["together"]},
  "یکدگه": {"say": "yak-di-ga", "mean": ["each other"]},
  "یکی": {"say": "ya-kee", "mean": ["one of them"]},
  "یکیش": {"say": "ya-keesh", "mean": ["one of them"]},
  "یگانه": {"say": "ya-gaa-na", "mean": ["only, single"]}
};
